import React,{useEffect,useState} from 'react';
import {readUtf8Source} from './intakeFiles';

export function CopilotPanel({process,busy,onSubmit}:{process?:{id:string;status:string;llm?:any};busy:boolean;onSubmit:(analysis:unknown,processId:string)=>Promise<void>}){
 const [file,setFile]=useState<File|null>(null),[error,setError]=useState('');
 useEffect(()=>{setFile(null);setError('');},[process?.id]);
 async function submit(){if(!file||!process)return;setError('');try{const analysis=JSON.parse(await readUtf8Source(file,128000));if(!analysis||typeof analysis!=='object'||Array.isArray(analysis))throw Error('Return a structured Copilot analysis JSON object.');await onSubmit(analysis,process.id);}catch(failure){setError(failure instanceof Error?failure.message:'The analysis return could not be read.');}}
 return <section><p className="eyebrow">GITHUB COPILOT CHAT</p><h2>Return analysis before the one SME packet</h2><p>Use the existing workbench MCP bridge from VS Code. Source-grounded suggestions do not implement an adapter, answer for a human, or establish mainframe parity.</p>{!process?<p className="notice">Select a process with completed lineage discovery first.</p>:<><ol className="setup-steps"><li>Open this repository in VS Code. Use <code>examples/mcp.json</code> as the project template for <code>.vscode/mcp.json</code>, or select the approved existing IDE configuration. Supply the actual Python interpreter and running loopback workbench origin when prompted.</li><li>Ask Copilot Chat to call <code>workbench_next_task</code> for process <code>{process.id}</code>, inspect <code>workbench_lineage</code>, and retrieve any required evidence with <code>workbench_source_excerpt</code>.</li><li>Ask it to address every named adapter gap with source-supported implementation work and meaningful tests, retaining missing evidence as a blocker. After implementation, call <code>workbench_refresh_analysis</code> and retrieve a fresh <code>workbench_next_task</code> before preparing the return.</li><li>Return the structured suggestions through <code>workbench_submit_analysis</code>. The Coordinator validates frozen hashes and source references before issuing the single SME packet.</li></ol><p className="notice">Copilot model identity and token usage: <strong>Unknown</strong>. Only self-reported attribution is available; this bridge does not observe IDE model counters.</p>{process.status==='WAITING_COPILOT'?<><a className="download" href={`/api/process/${encodeURIComponent(process.id)}/agent/task`} target="_blank" rel="noreferrer">Inspect frozen Copilot task JSON<span className="sr-only"> (opens in a new tab)</span></a><details><summary>Import a structured analysis return manually</summary><p>Use the task’s return contract and frozen hashes. This accepts suggestions only; it does not import SME answers or commands.</p><label>Copilot analysis return (.json, at most 128,000 bytes)<input key={process.id} type="file" accept=".json" disabled={busy} onChange={event=>{setFile(event.target.files?.[0]||null);setError('');}}/></label>{error&&<p className="error" role="alert">{error}</p>}<button className="primary" disabled={busy||!file} onClick={()=>void submit()}>{busy?'Validating return…':'Validate analysis return'}</button></details></>:<p className="notice">{process.llm?.status==='AGENT_ANALYSIS_RETURNED'?'The structured Copilot return is recorded. Actual human SME review and deterministic verification remain separate gates.':'The task becomes available when the process is waiting for Copilot after lineage discovery.'}</p>}</>}</section>;
}
