import React,{useEffect,useRef,useState} from 'react';
const value=(v:unknown)=>v===null||v===undefined?'Unknown':String(v);
const units=[['process','Business processes'],['jcl_procs','JCL PROCs'],['jcl_jobs','JCL jobs'],['batch_cobol','Batch COBOL programs'],['copybooks','Copybooks'],['cics_screens','CICS screens'],['db2_tables','Db2 tables'],['ca7_schedules','CA7 schedules'],['mq','MQ interfaces']];

export function EconomicsSummary({model}:{model:any}){
 const forecast=model.forecast,pilot=model.processes?.[0];
 return <><div className="summary-grid"><div><span>Pilot effort hours</span><strong>{value(pilot?.work.total_effort_hours)}</strong><small>{pilot?.work.complete?'Attributed complete effort receipt':'Complete effort has not been established'}</small></div><div><span>Observed service hours</span><strong>{value(pilot?.timing.service_hours)}</strong><small>Elapsed process hours: {value(pilot?.timing.elapsed_hours)}</small></div><div><span>Framework investment hours</span><strong>{value(model.framework?.recorded_detail_hours)}</strong><small>One-time work, excluded from conversion rates</small></div></div>
 <p>As of {model.as_of}. {model.boundary}</p>{model.integrity_errors?.length>0&&<p role="alert">Measurement evidence failed integrity checks. Forecast unavailable: {model.integrity_errors.join(', ')}</p>}
 {model.framework?.issues?.map((s:string)=><p role="alert" key={s}>Framework work: {s}</p>)}{pilot?.demo&&<p>Fictional demonstration. Excluded from completed-pilot calibration.</p>} {pilot?.work.issues?.map((s:string)=><p role="alert" key={s}>{s}</p>)}
 {model.forecast_errors?.map((s:string)=><p role="alert" key={s}>Forecast needs updating: {s}</p>)}<h3>Estimate for the remaining estate</h3>{forecast?<><p><strong>{value(forecast.remaining_effort_hours.base)} hours</strong> at the base rate · range {value(forecast.remaining_effort_hours.low)}–{value(forecast.remaining_effort_hours.high)} hours · {value(forecast.capacity_weeks.base)} capacity weeks. {forecast.unestimated_units} units still have no estimate.</p><div className="table-scroll"><table><thead><tr><th>Cohort / unit</th><th>Remaining</th><th>Measured pilots</th><th>Basis</th><th>Base hours</th></tr></thead><tbody>{forecast.cohorts.map((r:any)=><tr key={r.id}><th>{r.id} / {r.unit}</th><td>{r.remaining_units}</td><td>{r.sample_size}</td><td>{r.basis.replaceAll('_',' ')}</td><td>{value(r.remaining_effort_hours.base)}</td></tr>)}</tbody></table></div><p>{forecast.boundary}</p>{forecast.cohorts.map((r:any)=>r.observed_component_projections&&<p key={r.id}>Observed service projection: {value(r.observed_component_projections.service_hours.remaining_sequential_hours?.base)} hours; sequential elapsed projection: {value(r.observed_component_projections.elapsed_hours.remaining_sequential_hours?.base)} hours. {r.component_boundary}</p>)}{forecast.cohorts.flatMap((r:any)=>(r.remaining_ai_usage||[]).map((a:any)=><p key={[r.id,a.provider,a.account,a.unit].join('/')}>{a.basis==='ASSUMPTION'?'Assumed':'Pilot-derived'} remaining AI credits: {a.provider} / {a.account} — {a.remaining.base} {a.unit} ({a.remaining.low}–{a.remaining.high}).</p>))}</>:<p>Unknown. Add estate quantity, a comparable pilot or rate assumption, and available capacity.</p>}
 <h3>GitHub Copilot credits used</h3>{model.usage?.copilot_credits?.accounts.length?model.usage.copilot_credits.accounts.map((r:any)=><p key={r.provider+r.account}><strong>{r.credits_used} credits</strong> · {r.account}</p>):<p>Unknown. No actual GitHub Copilot credits receipt has been recorded for this scope.</p>}<p>{model.usage?.copilot_credits?.basis}</p><details><summary>Other recorded usage and optional allowance</summary><h3>AI usage and allowance</h3>{model.usage?.quantities.length?<div className="table-scroll"><table><thead><tr><th>Provider / account / model</th><th>Unit</th><th>Recorded usage</th><th>Evidence</th></tr></thead><tbody>{model.usage.quantities.map((r:any,i:number)=><tr key={i}><th>{r.provider} / {r.account} / {r.model}</th><td>{r.unit}</td><td>{r.quantity}</td><td>{r.provenance}</td></tr>)}</tbody></table></div>:<p>Usage: Unknown. No actual usage receipt or provider counters have been recorded for this scope.</p>}
 {model.usage?.budgets.length?model.usage.budgets.map((b:any)=><p key={b.receipt_id}><strong>{b.provider} / {b.account}</strong>: {b.remaining_at_snapshot} {b.unit} remaining at {b.snapshot_at}; allowance {b.allowance}, consumed {b.consumed_at_snapshot}. Conditional remaining: {value(b.conditional_remaining)}. {b.expired?'The budget period has ended. ':''}{b.basis}</p>):<p>Allowance and remaining credits: Unknown. Import an actual account snapshot to establish the budget.</p>}
 {model.usage?.issues?.map((r:any,i:number)=><p role="alert" key={i}>{r.provider} / {r.account}: {r.message}</p>)}<p>{model.usage?.boundary}</p></details><details><summary>Migration evidence used for learning ({model.learning_count??0})</summary><p>Comparability depends on the actual scope. Blocked or changed evidence cannot establish a completed-pilot rate.</p><div className="table-scroll"><table><thead><tr><th>Process</th><th>Status</th><th>Jobs / programs / rules</th><th>Outputs / test runs</th><th>Gaps</th><th>Effort eligible</th></tr></thead><tbody>{model.learning?.map((r:any)=><tr key={r.process_id}><th>{r.process_id}</th><td>{r.status}</td><td>{r.jobs} / {r.programs} / {r.rules}</td><td>{r.artifact_count} / {r.verification_runs}</td><td>{r.open_gaps}</td><td>{r.effort_calibration_eligible?'Yes':'No'}</td></tr>)}</tbody></table></div>{model.learning_truncated&&<p>Showing the latest 50 pilots. Forecasts use all eligible members of the selected cohort.</p>}</details><details><summary>Work stages, waits and open timing records</summary><p>Unfinished service attempts: {pilot?.timing.unfinished_attempts??0}. Open or unmeasured agent sessions: {model.work_sessions?.length??0}. {pilot?.timing.boundary}</p><table><thead><tr><th>Measure</th><th>Hours</th></tr></thead><tbody>{[['Recorded work',pilot?.work.by_stage],['Observed service',pilot?.timing.service_by_stage],['Wall-clock status',pilot?.timing.status_hours]].flatMap(([label,rows]:any)=>Object.entries(rows||{}).map(([k,v])=><tr key={label+k}><th>{label}: {k}</th><td>{value(v)}</td></tr>))}</tbody></table><p>Stage work is included in the whole-pilot total. Service execution and status time can overlap and must not be added to work effort.</p></details></>;
}

export function EconomicsPanel({processId,token}:{processId?:string;token:string}){
 const [model,setModel]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0),[unit,setUnit]=useState('process'),[total,setTotal]=useState(''),[low,setLow]=useState(''),[base,setBase]=useState(''),[high,setHigh]=useState(''),[capacity,setCapacity]=useState(''),[feedback,setFeedback]=useState('');
 const lock=useRef(false);
 useEffect(()=>{const controller=new AbortController();setModel(null);setError('');fetch('/api/economics'+(processId?'?process_id='+encodeURIComponent(processId):''),{signal:controller.signal}).then(async r=>{const data=await r.json();if(!r.ok)throw new Error(data.error||'Could not load measurements');return data;}).then(data=>{if(!controller.signal.aborted)setModel(data);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[processId,revision]);
 async function post(url:string,body:any){const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json','X-Workbench-Token':token},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.error||'Could not save measurement');return data;}
 async function perform(action:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);setError('');setFeedback('');try{await action();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{lock.current=false;setBusy(false);}}
 function plan(){if(!total.trim())throw new Error('Enter the total estate quantity for the selected unit.');const rates=low||base||high?{hours_per_unit:{low,base,high}}:{};return {cohorts:[{id:unit,unit,total:Number(total),...rates}],...(capacity?{capacity_hours_per_week:capacity}:{})};}
 return <section className="panel"><div className="sectionhead"><div><p className="eyebrow">PILOT TO ESTATE</p><h2>Effort, AI usage and scale</h2></div><button disabled={busy} onClick={()=>setRevision(r=>r+1)}>Refresh measurements</button></div>{error&&<p role="alert">{error}</p>}{feedback&&<p role="status">{feedback}</p>}{model?<EconomicsSummary model={model}/>:<p role="status">Loading measured effort…</p>}
 <details><summary>Set the estate scenario</summary><p>Use the same unit as the measured pilot. A 20-hour process does not establish a 20-hour rate for each PROC or program. Leave rate fields empty to use eligible completed process receipts.</p><form onSubmit={e=>{e.preventDefault();void perform(async()=>{setModel(await post('/api/economics/forecast',{process_id:processId,plan:plan()}));setFeedback('Scenario preview only. Save to use it in future reports.');});}}><label>Counting unit<select value={unit} onChange={e=>setUnit(e.target.value)}>{units.map(([k,label])=><option value={k} key={k}>{label}</option>)}</select></label><label>Total estate quantity<input type="number" min="0" step="1" value={total} onChange={e=>setTotal(e.target.value)} required/></label><div className="summary-grid">{[['Low hours per unit',low,setLow],['Base hours per unit',base,setBase],['High hours per unit',high,setHigh]].map(([label,v,set]:any)=><label key={label}>{label}<input type="number" min="0.000001" step="any" value={v} onChange={e=>set(e.target.value)}/></label>)}</div><label>Combined productive capacity (hours/week)<input type="number" min="0.000001" step="any" value={capacity} onChange={e=>setCapacity(e.target.value)}/></label><button disabled={busy} type="submit">Preview estimate</button> <button type="button" disabled={busy} onClick={()=>void perform(async()=>{await post('/api/economics/receipts',{id:'plan-'+crypto.randomUUID(),kind:'plan',process_id:null,evidence:'Operator-entered estate assumptions from the workbench UI',recorded_by:'local workbench session',plan:plan()});setRevision(r=>r+1);setFeedback('Scenario saved for future reports. Existing issued reports retain their original measurements.');})}>Save scenario</button></form></details>
 <details><summary>Import work or AI account evidence</summary><p>Import an attributed JSON work, usage or budget receipt following the technical reference. Use a stable receipt ID so retries cannot double-count. The agent can record these through the same MCP bridge.</p><label>Measurement receipt<input type="file" accept=".json,application/json" disabled={busy} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)void perform(async()=>{if(file.size>65536)throw new Error('Measurement exceeds 64 KiB');const raw=await file.text();if(new TextEncoder().encode(raw).length>65536)throw new Error('Measurement exceeds 64 KiB');await post('/api/economics/receipts',JSON.parse(raw));setRevision(r=>r+1);setFeedback('Attributed evidence recorded.');});}}/></label></details></section>;
}
