import React,{useEffect,useRef,useState} from 'react';
import {fieldErrorFeedback} from './formAccessibility';
import {WorkSessionControls,workSessionStart,workSessionStopFeedback,type WorkSessionStart,type WorkSessionStop} from './WorkSessionControls';
const value=(v:unknown)=>v===null||v===undefined?'Unknown':String(v);
const units=[['process','Business processes'],['jcl_procs','JCL PROCs'],['jcl_jobs','JCL jobs'],['batch_cobol','Batch COBOL programs'],['copybooks','Copybooks'],['cics_screens','CICS screens'],['db2_tables','Db2 tables'],['ca7_schedules','CA7 schedules'],['mq','MQ interfaces']];

export function EconomicsSummary({model}:{model:any}){
 const forecast=model.forecast,pilot=model.processes?.[0];
 return <><div className="summary-grid"><div><span>Pilot effort hours</span><strong>{value(pilot?.work.total_effort_hours)}</strong><small>{pilot?.work.complete?'Attributed complete effort receipt':'Complete effort has not been established'}</small></div><div><span>Observed service hours</span><strong>{value(pilot?.timing.service_hours)}</strong><small>Elapsed process hours: {value(pilot?.timing.elapsed_hours)}</small></div><div><span>Framework investment hours</span><strong>{value(model.framework?.recorded_detail_hours)}</strong><small>One-time work, excluded from conversion rates</small></div></div>
 <p>As of {model.as_of}. {model.boundary}</p>{model.integrity_errors?.length>0&&<p role="alert">Measurement evidence failed integrity checks. Forecast unavailable: {model.integrity_errors.join(', ')}</p>}
 {model.framework?.issues?.map((s:string)=><p role="alert" key={s}>Framework work: {s}</p>)}{pilot?.demo&&<p>Fictional demonstration. Excluded from completed-pilot calibration.</p>} {pilot?.work.issues?.map((s:string)=><p role="alert" key={s}>{s}</p>)}
 {model.forecast_errors?.map((s:string)=><p role="alert" key={s}>Forecast needs updating: {s}</p>)}<h3>Estimate for the remaining estate</h3>{forecast?<><p><strong>{value(forecast.remaining_effort_hours.base)} hours</strong> at the base rate · range {value(forecast.remaining_effort_hours.low)}–{value(forecast.remaining_effort_hours.high)} hours · {value(forecast.capacity_weeks.base)} capacity weeks. {forecast.unestimated_units} units still have no estimate.</p><div className="table-scroll" role="region" aria-label="Estate forecast cohorts" tabIndex={0}><table><thead><tr><th scope="col">Cohort / unit</th><th scope="col">Remaining</th><th scope="col">Measured pilots</th><th scope="col">Basis</th><th scope="col">Base hours</th></tr></thead><tbody>{forecast.cohorts.map((r:any)=><tr key={r.id}><th scope="row">{r.id} / {r.unit}</th><td>{r.remaining_units}</td><td>{r.sample_size}</td><td>{r.basis.replaceAll('_',' ')}</td><td>{value(r.remaining_effort_hours.base)}</td></tr>)}</tbody></table></div><p>{forecast.boundary}</p>{forecast.cohorts.map((r:any)=>r.observed_component_projections&&<p key={r.id}>Observed service projection: {value(r.observed_component_projections.service_hours.remaining_sequential_hours?.base)} hours; sequential elapsed projection: {value(r.observed_component_projections.elapsed_hours.remaining_sequential_hours?.base)} hours. {r.component_boundary}</p>)}{forecast.cohorts.flatMap((r:any)=>(r.remaining_ai_usage||[]).map((a:any)=><p key={[r.id,a.provider,a.account,a.unit].join('/')}>{a.basis==='ASSUMPTION'?'Assumed':'Pilot-derived'} remaining AI credits: {a.provider} / {a.account} — {a.remaining.base} {a.unit} ({a.remaining.low}–{a.remaining.high}).</p>))}</>:<p>Unknown. Add estate quantity, a comparable pilot or rate assumption, and available capacity.</p>}
 <h3>GitHub Copilot credits used</h3>{model.usage?.copilot_credits?.accounts.length?model.usage.copilot_credits.accounts.map((r:any)=><p key={r.provider+r.account}><strong>{r.credits_used} credits</strong> · {r.account}</p>):<p>Unknown. No actual GitHub Copilot credits receipt has been recorded for this scope.</p>}<p>{model.usage?.copilot_credits?.basis}</p><details><summary>Other recorded usage and optional allowance</summary><h3>AI usage and allowance</h3>{model.usage?.quantities.length?<div className="table-scroll" role="region" aria-label="Recorded AI usage" tabIndex={0}><table><thead><tr><th scope="col">Provider / account / model</th><th scope="col">Unit</th><th scope="col">Recorded usage</th><th scope="col">Evidence</th></tr></thead><tbody>{model.usage.quantities.map((r:any,i:number)=><tr key={i}><th scope="row">{r.provider} / {r.account} / {r.model}</th><td>{r.unit}</td><td>{r.quantity}</td><td>{r.provenance}</td></tr>)}</tbody></table></div>:<p>Usage: Unknown. No actual usage receipt or provider counters have been recorded for this scope.</p>}
 {model.usage?.budgets.length?model.usage.budgets.map((b:any)=><p key={b.receipt_id}><strong>{b.provider} / {b.account}</strong>: {b.remaining_at_snapshot} {b.unit} remaining at {b.snapshot_at}; allowance {b.allowance}, consumed {b.consumed_at_snapshot}. Conditional remaining: {value(b.conditional_remaining)}. {b.expired?'The budget period has ended. ':''}{b.basis}</p>):<p>Allowance and remaining credits: Unknown. Import an actual account snapshot to establish the budget.</p>}
 {model.usage?.issues?.map((r:any,i:number)=><p role="alert" key={i}>{r.provider} / {r.account}: {r.message}</p>)}<p>{model.usage?.boundary}</p></details><details><summary>Migration evidence used for learning ({model.learning_count??0})</summary><p>Comparability depends on the actual scope. Blocked or changed evidence cannot establish a completed-pilot rate.</p><div className="table-scroll" role="region" aria-label="Pilot learning evidence" tabIndex={0}><table><thead><tr><th scope="col">Process</th><th scope="col">Status</th><th scope="col">Jobs / programs / rules</th><th scope="col">Outputs / test runs</th><th scope="col">Gaps</th><th scope="col">Effort eligible</th></tr></thead><tbody>{model.learning?.map((r:any)=><tr key={r.process_id}><th scope="row">{r.process_id}</th><td>{r.status}</td><td>{r.jobs} / {r.programs} / {r.rules}</td><td>{r.artifact_count} / {r.verification_runs}</td><td>{r.open_gaps}</td><td>{r.effort_calibration_eligible?'Yes':'No'}</td></tr>)}</tbody></table></div>{model.learning_truncated&&<p>Showing the latest 50 pilots. Forecasts use all eligible members of the selected cohort.</p>}</details><details><summary>Work stages, waits and open timing records</summary><p>Unfinished service attempts: {pilot?.timing.unfinished_attempts??0}. Open or unmeasured agent sessions: {model.work_sessions?.length??0}. {pilot?.timing.boundary}</p><div className="table-scroll" role="region" aria-label="Measured work stages" tabIndex={0}><table><thead><tr><th scope="col">Measure</th><th scope="col">Hours</th></tr></thead><tbody>{[['Recorded work',pilot?.work.by_stage],['Observed service',pilot?.timing.service_by_stage],['Wall-clock status',pilot?.timing.status_hours]].flatMap(([label,rows]:any)=>Object.entries(rows||{}).map(([k,v])=><tr key={label+k}><th scope="row">{label}: {k}</th><td>{value(v)}</td></tr>))}</tbody></table></div><p>Stage work is included in the whole-pilot total. Service execution and status time can overlap and must not be added to work effort.</p></details></>;
}

class MeasurementHttpError extends Error {constructor(public status:number,message:string){super(message);}}

export function EconomicsPanel({processId,token}:{processId?:string;token:string}){
 const [model,setModel]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0),[unit,setUnit]=useState('process'),[total,setTotal]=useState(''),[low,setLow]=useState(''),[base,setBase]=useState(''),[high,setHigh]=useState(''),[capacity,setCapacity]=useState(''),[feedback,setFeedback]=useState(''),[invalidField,setInvalidField]=useState('');
 const scenarioForm=useRef<HTMLFormElement>(null),errorSummary=useRef<HTMLParagraphElement>(null);
 const lock=useRef(false),pendingWorkRef=useRef<WorkSessionStart|null>(null),pendingStopRef=useRef<WorkSessionStop|null>(null);
 const [pendingWork,setPendingWork]=useState<WorkSessionStart|null>(null),[pendingStop,setPendingStop]=useState<WorkSessionStop|null>(null);
 useEffect(()=>{const controller=new AbortController();setModel(null);setLoading(true);setError('');fetch('/api/economics'+(processId?'?process_id='+encodeURIComponent(processId):''),{signal:controller.signal}).then(async r=>{const data=await r.json();if(!r.ok)throw new Error(data.error||'Could not load measurements');return data;}).then(data=>{if(!controller.signal.aborted)setModel(data);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[processId,revision]);
 async function post(url:string,body:any){const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json','X-Workbench-Token':token},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new MeasurementHttpError(response.status,data.error||'Could not save measurement');return data;}
 async function perform(action:()=>Promise<void>,focusScenario=false){if(lock.current)return;lock.current=true;setBusy(true);setError('');setInvalidField('');setFeedback('');try{await action();}catch(e){setError(e instanceof Error?e.message:String(e));requestAnimationFrame(()=>{const invalid=focusScenario?scenarioForm.current?.querySelector<HTMLInputElement>('input:invalid'):null;if(invalid)invalid.focus();else errorSummary.current?.focus();});}finally{lock.current=false;setBusy(false);}}
 function startWork(actor:string,stage:string){void perform(async()=>{
  const request=pendingWorkRef.current??workSessionStart(processId,actor,stage);pendingWorkRef.current=request;setPendingWork(request);
  let result;try{result=await post('/api/economics/work/start',request);}catch(error){if(error instanceof MeasurementHttpError&&error.status>=400&&error.status<500&&![408,429].includes(error.status)){pendingWorkRef.current=null;setPendingWork(null);}throw error;}
  pendingWorkRef.current=null;setPendingWork(null);setRevision(r=>r+1);setFeedback(result.receipt_id?'Existing work-window outcome confirmed.':'Work window started. Stop it before waiting on a human or restarting.');
 });}
 function stopWork(id:string,abandon:boolean){void perform(async()=>{
  const request=pendingStopRef.current??Object.freeze({id,abandon});pendingStopRef.current=request;setPendingStop(request);
  let result;try{result=await post('/api/economics/work/stop',request);}catch(error){if(error instanceof MeasurementHttpError&&error.status>=400&&error.status<500&&![408,429].includes(error.status)){pendingStopRef.current=null;setPendingStop(null);}throw error;}
  const message=workSessionStopFeedback(result);pendingStopRef.current=null;setPendingStop(null);setRevision(r=>r+1);setFeedback(message);
 });}
 function plan(){const invalid=scenarioForm.current?.querySelector<HTMLInputElement>('input:invalid');if(invalid){setInvalidField(invalid.id);const label=invalid.labels?.[0]?.firstChild?.textContent?.trim()||'This field';throw new Error(label+': '+(invalid.validationMessage||'Enter a valid value.'));}if(!total.trim())throw new Error('Enter the total estate quantity for the selected unit.');const rates=low||base||high?{hours_per_unit:{low,base,high}}:{};return {cohorts:[{id:unit,unit,total:Number(total),...rates}],...(capacity?{capacity_hours_per_week:capacity}:{})};}
 return <section className="panel"><div className="sectionhead"><div><p className="eyebrow">PILOT TO ESTATE</p><h2>Effort, AI usage and scale</h2></div><button disabled={busy} onClick={()=>setRevision(r=>r+1)}>Refresh measurements</button></div>{error&&<p id="economics-form-error" ref={errorSummary} tabIndex={-1} role="alert">{error}</p>}{feedback&&<p role="status">{feedback}</p>}{model?<EconomicsSummary model={model}/>:loading?<p role="status">Loading measured effort…</p>:<p>Measurements are unavailable. Refresh measurements to try again.</p>}
 <WorkSessionControls key={processId||'workspace'} processId={processId} sessions={model?.work_sessions||[]} disabled={busy||!token||!model} pending={pendingWork} pendingStop={pendingStop} onStart={startWork} onStop={stopWork}/><details><summary>Set the estate scenario</summary><p>Use the same unit as the measured pilot. A 20-hour process does not establish a 20-hour rate for each PROC or program. Leave rate fields empty to use eligible completed process receipts.</p><form ref={scenarioForm} noValidate onSubmit={e=>{e.preventDefault();void perform(async()=>{setModel(await post('/api/economics/forecast',{process_id:processId,plan:plan()}));setFeedback('Scenario preview only. Save to use it in future reports.');},true);}}><label>Counting unit<select disabled={busy} value={unit} onChange={e=>setUnit(e.target.value)}>{units.map(([k,label])=><option value={k} key={k}>{label}</option>)}</select></label><label htmlFor="economics-total">Total estate quantity<input {...fieldErrorFeedback('economics-total',invalidField,'economics-form-error')} id="economics-total" type="number" min="0" max="100000000" step="1" disabled={busy} value={total} onChange={e=>setTotal(e.target.value)} required/></label><div className="summary-grid">{[['Low hours per unit',low,setLow,'low'],['Base hours per unit',base,setBase,'base'],['High hours per unit',high,setHigh,'high']].map(([label,v,set,key]:any)=><label key={label} htmlFor={'economics-'+key}>{label}<input {...fieldErrorFeedback('economics-'+key,invalidField,'economics-form-error')} id={'economics-'+key} type="number" min="1e-30" max="1e15" step="any" required={!!(low||base||high)} disabled={busy} value={v} onChange={e=>set(e.target.value)}/></label>)}</div><label htmlFor="economics-capacity">Combined productive capacity (hours/week)<input {...fieldErrorFeedback('economics-capacity',invalidField,'economics-form-error')} id="economics-capacity" type="number" min="1e-30" max="1e15" step="any" disabled={busy} value={capacity} onChange={e=>setCapacity(e.target.value)}/></label><button disabled={busy} type="submit">Preview estimate</button> <button type="button" disabled={busy} onClick={()=>void perform(async()=>{await post('/api/economics/receipts',{id:'plan-'+crypto.randomUUID(),kind:'plan',process_id:null,evidence:'Operator-entered estate assumptions from the workbench UI',recorded_by:'local workbench session',plan:plan()});setRevision(r=>r+1);setFeedback('Scenario saved for future reports. Existing issued reports retain their original measurements.');},true)}>Save scenario</button></form></details>
 <details><summary>Import work or AI account evidence</summary><p>Import an attributed JSON work, usage or budget receipt following the technical reference. Use a stable receipt ID so retries cannot double-count. Claude records actual attributed receipts with <code>python -m workbench.runner agent PROCESS_ID --workspace WORKSPACE --measurement-file RECEIPT_JSON</code>. With the UI running, its Coordinator consumes the local command inbox. Claude uses no MCP servers; Copilot retrieves evidence through approved connections.</p><label>Measurement receipt<input type="file" accept=".json,application/json" disabled={busy} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)void perform(async()=>{if(file.size>65536)throw new Error('Measurement exceeds 64 KiB');const raw=await file.text();if(new TextEncoder().encode(raw).length>65536)throw new Error('Measurement exceeds 64 KiB');await post('/api/economics/receipts',JSON.parse(raw));setRevision(r=>r+1);setFeedback('Attributed evidence recorded.');});}}/></label></details></section>;
}
