import React,{useEffect,useRef,useState} from 'react';
import {artifactUrl} from './workflow';
import {usePolling} from './usePolling';

type Step={id:string;title:string;state:'complete'|'current'|'pending'|'blocked';description:string};
type Handoff={prompt:string;status:string;request_id?:string;return_folder?:string;task_file?:string|null;return_inbox?:string};
export type ProcessGuide={process_id:string;name:string;status:string;current_step:string;steps:Step[];next_action:{id:string;label:string;description:string;kind:'local_action'|'requirements'|'human_review'|'results'|'setup'|'wait';action?:string};handoffs:{retrieval:Handoff|null;claude:Handoff|null};markdown:null|{path:string;artifact:string;sha256:string};requirements:null|{path:string;artifact:string;sha256:string;revision:number};source:{retained_files:number;closure_complete:boolean;pending:number;source_directory:string};setup:{saved:boolean;markdown_path:string|null;markdown_sha256:string|null};results:{comparison_available:boolean;report_path:string|null;gap_count:number|null;native_parity_verified:false};input:{process_markdown_path:string|null;process_markdown_sha256:string|null;context_path:string|null}};

export function guideMatchesProcess(guide:ProcessGuide|null,processId:string){return !!guide&&guide.process_id===processId;}
export function guideReadIsCurrent(guide:ProcessGuide|null,processId:string,status:string,loading:boolean,error:string,uncertain=false){return guideMatchesProcess(guide,processId)&&guide?.status===status&&!loading&&!error&&!uncertain;}
export function guideActionPath(processId:string,action:string){
 const base=`/api/process/${encodeURIComponent(processId)}`;
 if(['continue','request','refresh'].includes(action))return `${base}/local-agent/${action}`;
 if(['start','resume'].includes(action))return `${base}/${action}`;
 throw Error('This process action is unavailable. Refresh the guide.');
}

// Preserve drafts during refresh; disable stale controls with caller-selected visibility.
export function GuideCurrentPanel({current,disabled=false,keepVisible=false,children}:{current:boolean;disabled?:boolean;keepVisible?:boolean;children:React.ReactNode}){
 return <fieldset className="guide-current-panel" disabled={!current||disabled} hidden={!current&&!keepVisible} aria-disabled={!current||disabled||undefined}>{children}</fieldset>;
}

export type GuidePhase='source'|'rules'|'build'|'review';
const phaseGroups:{id:GuidePhase;title:string;steps:string[]}[]=[{id:'source',title:'Source & mapping',steps:['setup','process','retrieve']},{id:'rules',title:'Choose rules',steps:['scope']},{id:'build',title:'Build & test',steps:['build']},{id:'review',title:'Review & compare',steps:['review','verify','results']}];
export function guidePhase(step:string):GuidePhase{return phaseGroups.find(group=>group.steps.includes(step))?.id||'source';}
export function groupedGuideSteps(steps:Step[],currentStep:string){return phaseGroups.map(group=>{const children=steps.filter(step=>group.steps.includes(step.id));return {...group,details:children,state:children.some(step=>step.state==='blocked')?'blocked':group.id===guidePhase(currentStep)?'current':children.length>0&&children.every(step=>step.state==='complete')?'complete':'pending'};});}
export function ProcessGuideSteps({steps,currentStep,selectedPhase,onInspect}:{steps:Step[];currentStep:string;selectedPhase?:GuidePhase;onInspect?:(phase:GuidePhase)=>void}){
 return <ol className="process-guide-steps" aria-label="Four process stages">{groupedGuideSteps(steps,currentStep).map((step,index)=><li key={step.id} className={step.state} aria-current={step.id===guidePhase(currentStep)?'step':undefined}><button type="button" aria-pressed={selectedPhase===step.id} onClick={()=>onInspect?.(step.id)}><span className="guide-step-number" aria-hidden="true">{step.state==='complete'?'✓':index+1}</span><span><strong>{step.title}</strong><small>{step.state==='complete'?'Recorded':step.state==='current'?'Current stage':step.state==='blocked'?'Needs attention':'Not recorded yet'}</small><span className="sr-only">{step.details.map(item=>`${item.title}: ${item.description}`).join('; ')}</span></span></button></li>)}</ol>;
}

export function GuidePrompt({role,handoff,disabled,onCopy}:{role:'Retrieval'|'Claude';handoff:Handoff;disabled:boolean;onCopy:()=>void}){
 const label=role==='Retrieval'?'Copy retrieval prompt to Claude Code':'Copy analysis, development and test prompt to Claude Code';
 return <article className="guide-prompt"><div className="sectionhead"><div><p className="eyebrow">{role==='Retrieval'?'CLAUDE CODE · APPROVED RETRIEVAL':'CLAUDE CODE · LOCAL ANALYSIS & BUILD'}</p><h3>{role==='Retrieval'?'Retrieve the requested evidence':'Analyze, build and test this process'}</h3></div><button disabled={disabled||!handoff.prompt} onClick={onCopy}>Copy {role==='Retrieval'?'Claude retrieval':'Claude'} prompt</button></div><p>{role==='Retrieval'?'Paste this exact prompt into Claude Code. It uses approved read-only Zowe CLI and Db2 MCP and saves evidence in the request’s inbox. Raw records stay local for programmatic comparison.':'Paste this exact prompt into Claude Code. It reads the current safe task, approved metadata and explicitly approved sanitized views, then develops, tests and reviews locally. Private records, source literals and derived artifacts stay outside model context.'}</p><label>{label}<textarea readOnly rows={9} className="guide-prompt-text" value={handoff.prompt}/></label>{handoff.return_folder&&<p><strong>Return files to</strong><br/><code>{handoff.return_folder}</code></p>}{handoff.return_inbox&&<p><strong>Analysis return inbox</strong><br/><code>{handoff.return_inbox}</code></p>}{handoff.task_file&&<details><summary>Current task file</summary><code>{handoff.task_file}</code></details>}{handoff.request_id&&<details><summary>Request identity</summary><code>{handoff.request_id}</code></details>}<p className="fine-print">{role==='Retrieval'?'After Claude saves the requested files, return here and continue from local files. Missing or denied objects remain visible.':'If Claude needs more evidence, return to the current Claude retrieval request. A development result cannot answer the separate human SME packet.'}</p></article>;
}

export function GuideWorkspaceSummary({model,onSave,disabled=false}:{model:ProcessGuide;onSave?:()=>void;disabled?:boolean}){
 return <details className="guide-evidence"><summary>Saved instructions and process evidence</summary><dl><dt>Process Markdown</dt><dd>{model.markdown?.artifact?<a href={artifactUrl(model.process_id,model.markdown?.artifact)}>Download saved process instructions</a>:'Save this guide to create the process instructions.'}{model.markdown?.path&&<><br/><code>{model.markdown?.path}</code></>}</dd><dt>Selected requirements</dt><dd>{model.requirements?<><a href={artifactUrl(model.process_id,model.requirements.artifact)}>Download requirements · revision {model.requirements.revision}</a><br/><code>{model.requirements.path}</code></>:'Default Yes choices have not been saved.'}</dd><dt>Retained source files</dt><dd>{model.source.retained_files} · {model.source.closure_complete?'Static dependency closure checked':'Dependencies still need evidence'}</dd><dt>Frozen source directory</dt><dd><code>{model.source.source_directory}</code></dd>{model.setup.markdown_path&&<><dt>Workspace setup instructions</dt><dd><code>{model.setup.markdown_path}</code></dd></>}{model.input.process_markdown_path&&<><dt>Supplied process knowledge</dt><dd><code>{model.input.process_markdown_path}</code></dd></>}{model.input.context_path&&<><dt>Frozen process context</dt><dd><code>{model.input.context_path}</code></dd></>}</dl>{model.markdown?.artifact&&onSave&&<button disabled={disabled} onClick={onSave}>Save current process instructions</button>}<p className="fine-print">Saved files and static closure do not establish successful conversion or observed mainframe parity.</p></details>;
}

export function GuidedProcess({processId,status,token,disabled=false,revision=0,onChanged,onSetup,onBusyChange,renderPanel}:{processId:string;status:string;token:string;disabled?:boolean;revision?:number;onChanged:()=>Promise<void>;onSetup:()=>void;onBusyChange?:(busy:boolean)=>void;renderPanel:(guide:ProcessGuide,onSaved:()=>void,phase:GuidePhase)=>React.ReactNode}){
 const [model,setModel]=useState<ProcessGuide|null>(null),[error,setError]=useState(''),[actionError,setActionError]=useState(''),[feedback,setFeedback]=useState(''),[loading,setLoading]=useState(true),[working,setWorking]=useState(false),[refresh,setRefresh]=useState(0),[uncertain,setUncertain]=useState(false),[inspected,setInspected]=useState<GuidePhase|null>(null);
 const scope=useRef(0),lock=useRef(false),notify=useRef(onBusyChange);notify.current=onBusyChange;
 useEffect(()=>{++scope.current;setModel(null);setError('');setActionError('');setFeedback('');setLoading(true);setUncertain(false);lock.current=false;setWorking(false);setInspected(null);return()=>{++scope.current;notify.current?.(false);};},[processId]);
 usePolling<ProcessGuide>(`/api/process/${encodeURIComponent(processId)}/guide`,value=>{if(!guideMatchesProcess(value,processId)){setError('The guide belongs to another process. Refresh this guide.');setLoading(false);return;}setModel(value);setError('');setLoading(false);setUncertain(false);},failure=>{setError(failure.message);setLoading(false);},4000,`${status}:${revision}:${refresh}`);
 useEffect(()=>{setLoading(true);},[status,revision]);
 const current=guideReadIsCurrent(model,processId,status,loading,error,uncertain),blocked=disabled||working||!current||uncertain;
 function reload(){setLoading(true);setError('');setRefresh(value=>value+1);}
 function savedRequirements(){setLoading(true);setFeedback('Requirements saved. Loading the next recorded step…');setRefresh(value=>value+1);void onChanged().catch(reason=>setActionError(reason instanceof Error?reason.message:'The latest process state could not be read. Refresh the guide.'));}
 async function mutate(kind:'save'|'action'){
  if(blocked||lock.current||!model)return;lock.current=true;setWorking(true);notify.current?.(true);setActionError('');setFeedback('');const version=scope.current;
  try{const url=kind==='save'?`/api/process/${encodeURIComponent(processId)}/guide/save`:guideActionPath(processId,model.next_action.action||'');const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json','X-Workbench-Token':token},body:'{}'});const data=await response.json();if(!response.ok)throw Error(data.error||data.detail||'The step could not be confirmed.');if(version!==scope.current)return;setLoading(true);setFeedback(kind==='save'?'Process instructions saved. Use the current prompt below.':'Local files checked. Loading the current checkpoint…');setRefresh(value=>value+1);await onChanged();}
  catch(reason){if(version===scope.current){setActionError(reason instanceof Error?reason.message:'The request outcome could not be confirmed.');setUncertain(true);setLoading(true);setRefresh(value=>value+1);}}
  finally{if(version===scope.current){lock.current=false;setWorking(false);notify.current?.(false);}}
 }
 async function copy(role:'Retrieval'|'Claude'){
  if(blocked||!model?.markdown?.artifact)return;const prompt=model.handoffs[role==='Retrieval'?'retrieval':'claude']?.prompt;if(!prompt)return;const version=scope.current;setActionError('');try{await navigator.clipboard.writeText(prompt);if(version===scope.current)setFeedback(`${role} prompt copied. Use the exact local return location shown below.`);}catch{if(version===scope.current)setActionError('Clipboard access is unavailable. Select and copy the prompt text below.');}
 }
 const retained=guideMatchesProcess(model,processId),phase=inspected||guidePhase(model?.current_step||'process'),activePhase=guidePhase(model?.current_step||'process'),compactRules=phase==='rules'&&phase===activePhase&&model?.next_action.kind==='requirements';
 function inspect(next:GuidePhase){setInspected(next);setActionError('');setFeedback('');}
 return <div className="guided-process" aria-busy={loading||working}>
  <div className="guide-read-status" role="status">{loading?(retained?'Refreshing the checkpoint. Saved details stay visible; actions wait for the current read.':'Loading this process’s guide…'):!current&&retained?'Saved details are visible. Actions wait for a current checkpoint.':working?'Working on this step…':''}</div>
  {retained&&model&&<><ProcessGuideSteps steps={model.steps} currentStep={model.current_step} selectedPhase={phase} onInspect={inspect}/><div className="guide-navigation"><button disabled={phase==='source'} onClick={()=>inspect(phaseGroups[Math.max(0,phaseGroups.findIndex(item=>item.id===phase)-1)].id)}>Back</button>{phase!==activePhase&&<button onClick={()=>setInspected(null)}>Return to current stage</button>}<span>Viewing {phaseGroups.find(item=>item.id===phase)?.title}</span></div>
   <section className={compactRules?'guide-checkpoint-controls':'guide-next'}><div className="sectionhead">{!compactRules&&<div><h2>{phase===activePhase?model.next_action.label:phaseGroups.find(item=>item.id===phase)?.title}</h2>{phase===activePhase&&<p>{model.next_action.description}</p>}</div>}<button disabled={working||disabled} onClick={reload}>Refresh checkpoint</button></div>
    {phase===activePhase&&<><div className="form-actions">{!compactRules&&!model.markdown?.artifact&&<button className="primary" aria-describedby={actionError?'guide-action-error':undefined} disabled={blocked} onClick={()=>void mutate('save')}>{working?'Working…':'Save process instructions'}</button>}{model.next_action.kind==='local_action'&&model.next_action.action&&<button className="primary" aria-describedby={actionError?'guide-action-error':undefined} disabled={blocked} onClick={()=>void mutate('action')}>{model.next_action.label}</button>}{model.next_action.kind==='setup'&&<button className="primary" disabled={blocked} onClick={onSetup}>Inspect saved setup</button>}{model.results.report_path&&<a className="button primary" href={artifactUrl(processId,model.results.report_path,true)} target="_blank" rel="noreferrer">Open executive report<span className="sr-only"> (opens in a new tab)</span></a>}</div>{actionError&&<div id="guide-action-error" className="error" role="alert"><p>{actionError}</p>{uncertain&&<p>The action may have reached the Coordinator. Refresh this checkpoint before retrying.</p>}</div>}</>}
    {error&&<div className="error" role="alert"><p>{error}</p><p>Saved details remain visible. Current actions are disabled until connection is restored.</p><button disabled={working} onClick={reload}>Try loading this checkpoint again</button></div>}
    {phase==='source'&&<><p><strong>{model.source.retained_files}</strong> retained files · {model.source.closure_complete?'Dependencies mapped':'Dependency discovery in progress'}</p>{model.source.pending>0&&<p className="notice">{model.source.pending} dependencies need evidence. Claude checks local Endeavor first, then read-only Zowe and Db2 MCP. Conversion waits for unresolved items.</p>}<GuideWorkspaceSummary model={model} disabled={blocked} onSave={()=>void mutate('save')}/></>}
    {phase==='rules'&&!model.source.closure_complete&&<p>Rule choices become available after the job dependencies are mapped.</p>}{phase==='review'&&!model.results.comparison_available&&model.next_action.kind!=='human_review'&&<p>The single human review and accepted comparison appear here when the current build reaches their checkpoint.</p>}
    {phase!=='source'&&!compactRules&&<details><summary>Saved process evidence</summary><GuideWorkspaceSummary model={model} disabled={blocked} onSave={()=>void mutate('save')}/></details>}
   </section>
   {phase==='source'&&model.handoffs.retrieval&&<GuidePrompt role="Retrieval" handoff={model.handoffs.retrieval} disabled={blocked||!model.markdown?.artifact} onCopy={()=>void copy('Retrieval')}/>} {phase==='build'&&model.handoffs.claude&&<GuidePrompt role="Claude" handoff={model.handoffs.claude} disabled={blocked||!model.markdown?.artifact} onCopy={()=>void copy('Claude')}/>}<GuideCurrentPanel current={!!current} keepVisible disabled={disabled||working||uncertain}>{renderPanel(model,savedRequirements,phase)}</GuideCurrentPanel>
   {feedback&&<p role="status" className="guide-feedback">{feedback}</p>}{actionError&&phase!==activePhase&&<p id="guide-action-error" className="error" role="alert">{actionError}</p>}
  </>}
  {!retained&&error&&<div className="error" role="alert"><p>{error}</p><button disabled={working} onClick={reload}>Try loading this process again</button></div>}
 </div>;
}
