import React,{useEffect,useRef,useState} from 'react';
import {artifactUrl} from './workflow';
import {usePolling} from './usePolling';

type Step={id:string;title:string;state:'complete'|'current'|'pending'|'blocked';description:string};
type Handoff={prompt:string;status:string;request_id?:string;return_folder?:string;task_file?:string|null;return_inbox?:string};
export type ProcessGuide={process_id:string;name:string;status:string;current_step:string;steps:Step[];next_action:{id:string;label:string;description:string;kind:'local_action'|'requirements'|'human_review'|'results'|'setup'|'wait';action?:string};handoffs:{copilot:Handoff|null;claude:Handoff|null};markdown:null|{path:string;artifact:string;sha256:string};requirements:null|{path:string;artifact:string;sha256:string;revision:number};source:{retained_files:number;closure_complete:boolean;pending:number;source_directory:string};setup:{saved:boolean;markdown_path:string|null;markdown_sha256:string|null};results:{comparison_available:boolean;report_path:string|null;gap_count:number|null;native_parity_verified:false};input:{process_markdown_path:string|null;process_markdown_sha256:string|null;context_path:string|null}};

export function guideMatchesProcess(guide:ProcessGuide|null,processId:string){return !!guide&&guide.process_id===processId;}
export function guideReadIsCurrent(guide:ProcessGuide|null,processId:string,status:string,loading:boolean,error:string,uncertain=false){return guideMatchesProcess(guide,processId)&&guide?.status===status&&!loading&&!error&&!uncertain;}
export function guideActionPath(processId:string,action:string){
 const base=`/api/process/${encodeURIComponent(processId)}`;
 if(['continue','request','refresh'].includes(action))return `${base}/local-agent/${action}`;
 if(['start','resume'].includes(action))return `${base}/${action}`;
 throw Error('This process action is unavailable. Refresh the guide.');
}

// Keep draft-bearing panels mounted during a guide refresh, while hiding stale controls.
export function GuideCurrentPanel({current,disabled=false,children}:{current:boolean;disabled?:boolean;children:React.ReactNode}){
 return <fieldset className="guide-current-panel" disabled={!current||disabled} hidden={!current}>{children}</fieldset>;
}

export function ProcessGuideSteps({steps,currentStep}:{steps:Step[];currentStep:string}){
 return <ol className="process-guide-steps" aria-label="Guided process steps">{steps.map((step,index)=><li key={step.id} className={step.state} aria-current={step.id===currentStep?'step':undefined}><span className="guide-step-number" aria-hidden="true">{step.state==='complete'?'✓':index+1}</span><div><strong>{step.title}</strong><small>{step.state==='complete'?'Recorded':step.state==='current'?'Current step':step.state==='blocked'?'Needs attention':'Not recorded yet'}</small><span className="sr-only">{step.description}</span></div></li>)}</ol>;
}

export function GuidePrompt({role,handoff,disabled,onCopy}:{role:'Copilot'|'Claude';handoff:Handoff;disabled:boolean;onCopy:()=>void}){
 const label=role==='Copilot'?'Copy retrieval prompt to GitHub Copilot':'Copy analysis, development and test prompt to Claude Code';
 return <article className="guide-prompt"><div className="sectionhead"><div><p className="eyebrow">{role==='Copilot'?'COPILOT · PULL FILES ONLY':'CLAUDE CODE · LOCAL ANALYSIS & BUILD'}</p><h3>{role==='Copilot'?'Retrieve the requested evidence':'Analyze, build and test this process'}</h3></div><button disabled={disabled||!handoff.prompt} onClick={onCopy}>Copy {role} prompt</button></div><p>{role==='Copilot'?'Paste this exact prompt into GitHub Copilot in VS Code. It uses approved retrieval connections and saves original files in the request’s inbox.':'Paste this exact prompt into Claude Code. It reads the saved process instructions, local evidence and selected requirements, then develops, tests and reviews locally without MCP.'}</p><label>{label}<textarea readOnly rows={9} className="guide-prompt-text" value={handoff.prompt}/></label>{handoff.return_folder&&<p><strong>Return files to</strong><br/><code>{handoff.return_folder}</code></p>}{handoff.return_inbox&&<p><strong>Analysis return inbox</strong><br/><code>{handoff.return_inbox}</code></p>}{handoff.task_file&&<details><summary>Current task file</summary><code>{handoff.task_file}</code></details>}{handoff.request_id&&<details><summary>Request identity</summary><code>{handoff.request_id}</code></details>}<p className="fine-print">{role==='Copilot'?'After Copilot saves the requested files, return here and continue from local files. Missing or denied objects remain visible.':'If Claude needs more evidence, return to the current Copilot request. A development result cannot answer the separate human SME packet.'}</p></article>;
}

export function GuideWorkspaceSummary({model,onSave,disabled=false}:{model:ProcessGuide;onSave?:()=>void;disabled?:boolean}){
 return <details className="guide-evidence"><summary>Saved instructions and process evidence</summary><dl><dt>Process Markdown</dt><dd>{model.markdown?.artifact?<a href={artifactUrl(model.process_id,model.markdown?.artifact)}>Download saved process instructions</a>:'Save this guide to create the process instructions.'}{model.markdown?.path&&<><br/><code>{model.markdown?.path}</code></>}</dd><dt>Selected requirements</dt><dd>{model.requirements?<><a href={artifactUrl(model.process_id,model.requirements.artifact)}>Download requirements · revision {model.requirements.revision}</a><br/><code>{model.requirements.path}</code></>:'Default Yes choices have not been saved.'}</dd><dt>Retained source files</dt><dd>{model.source.retained_files} · {model.source.closure_complete?'Static dependency closure checked':'Dependencies still need evidence'}</dd><dt>Frozen source directory</dt><dd><code>{model.source.source_directory}</code></dd>{model.setup.markdown_path&&<><dt>Workspace setup instructions</dt><dd><code>{model.setup.markdown_path}</code></dd></>}{model.input.process_markdown_path&&<><dt>Supplied process knowledge</dt><dd><code>{model.input.process_markdown_path}</code></dd></>}{model.input.context_path&&<><dt>Frozen process context</dt><dd><code>{model.input.context_path}</code></dd></>}</dl>{model.markdown?.artifact&&onSave&&<button disabled={disabled} onClick={onSave}>Save current process instructions</button>}<p className="fine-print">Saved files and static closure do not establish successful conversion or observed mainframe parity.</p></details>;
}

export function GuidedProcess({processId,status,token,disabled=false,revision=0,onChanged,onSetup,onBusyChange,renderPanel}:{processId:string;status:string;token:string;disabled?:boolean;revision?:number;onChanged:()=>Promise<void>;onSetup:()=>void;onBusyChange?:(busy:boolean)=>void;renderPanel:(guide:ProcessGuide,onSaved:()=>void)=>React.ReactNode}){
 const [model,setModel]=useState<ProcessGuide|null>(null),[error,setError]=useState(''),[actionError,setActionError]=useState(''),[feedback,setFeedback]=useState(''),[loading,setLoading]=useState(true),[working,setWorking]=useState(false),[refresh,setRefresh]=useState(0),[uncertain,setUncertain]=useState(false);
 const scope=useRef(0),lock=useRef(false),notify=useRef(onBusyChange);notify.current=onBusyChange;
 useEffect(()=>{++scope.current;setModel(null);setError('');setActionError('');setFeedback('');setLoading(true);setUncertain(false);lock.current=false;setWorking(false);return()=>{++scope.current;notify.current?.(false);};},[processId]);
 usePolling<ProcessGuide>(`/api/process/${encodeURIComponent(processId)}/guide`,value=>{if(!guideMatchesProcess(value,processId)){setError('The guide belongs to another process. Refresh this guide.');setLoading(false);return;}setModel(value);setError('');setLoading(false);setUncertain(false);},failure=>{setError(failure.message);setLoading(false);},4000,`${status}:${revision}:${refresh}`);
 useEffect(()=>{setLoading(true);},[status,revision]);
 const current=guideReadIsCurrent(model,processId,status,loading,error,uncertain),blocked=disabled||working||!current||uncertain;
 function reload(){setLoading(true);setError('');setRefresh(value=>value+1);}
 function savedRequirements(){setLoading(true);setFeedback('Requirements saved. Loading the next recorded step…');setRefresh(value=>value+1);void onChanged().catch(reason=>setActionError(reason instanceof Error?reason.message:'The latest process state could not be read. Refresh the guide.'));}
 async function mutate(kind:'save'|'action'){
  if(blocked||lock.current||!model)return;lock.current=true;setWorking(true);notify.current?.(true);setActionError('');setFeedback('');const version=scope.current;
  try{const url=kind==='save'?`/api/process/${encodeURIComponent(processId)}/guide/save`:guideActionPath(processId,model.next_action.action||'');const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json','X-Workbench-Token':token},body:'{}'});const data=await response.json();if(!response.ok)throw Error(data.error||data.detail||'The step could not be confirmed.');if(version!==scope.current)return;setLoading(true);setFeedback(kind==='save'?'Process instructions saved. Use the current prompt below.':'Local files checked. Loading the current checkpoint…');setRefresh(value=>value+1);await onChanged();}
  catch(reason){if(version===scope.current){setActionError(reason instanceof Error?reason.message:'The request outcome could not be confirmed.');setUncertain(true);setLoading(true);setRefresh(value=>value+1);}}
  finally{if(version===scope.current){lock.current=false;setWorking(false);notify.current?.(false);}}
 }
 async function copy(role:'Copilot'|'Claude'){
  if(blocked||!model?.markdown?.artifact)return;const prompt=model.handoffs[role==='Copilot'?'copilot':'claude']?.prompt;if(!prompt)return;const version=scope.current;setActionError('');try{await navigator.clipboard.writeText(prompt);if(version===scope.current)setFeedback(`${role} prompt copied. Use the exact local return location shown below.`);}catch{if(version===scope.current)setActionError('Clipboard access is unavailable. Select and copy the prompt text below.');}
 }
 return <div className="guided-process" aria-busy={loading||working}>
  {loading&&<p role="status">Loading this process’s guide…</p>}
  {error&&<div className="error" role="alert"><p>{error}</p><p>Current prompts and actions are hidden until this process guide can be read.</p><button disabled={working} onClick={reload}>Try loading the guide again</button></div>}
  {current&&model&&<><ProcessGuideSteps steps={model.steps} currentStep={model.current_step}/><section className="guide-next"><div className="sectionhead"><div><p className="eyebrow">YOUR NEXT STEP</p><h2>{model.next_action.label}</h2><p>{model.next_action.description}</p></div><button disabled={working||disabled} onClick={reload}>Refresh guide</button></div><div className="form-actions">{!model.markdown?.artifact&&<button className="primary" disabled={blocked} onClick={()=>void mutate('save')}>{working?'Working…':'Save process instructions'}</button>}{model.next_action.kind==='local_action'&&model.next_action.action&&<button className="primary" disabled={blocked} onClick={()=>void mutate('action')}>{model.next_action.label}</button>}{model.next_action.kind==='setup'&&<button className="primary" disabled={blocked} onClick={onSetup}>Open workspace setup</button>}{model.results.report_path&&<a className="button primary" href={artifactUrl(processId,model.results.report_path,true)} target="_blank" rel="noreferrer">Open executive report<span className="sr-only"> (opens in a new tab)</span></a>}</div>{model.source.pending>0&&<p className="notice">{model.source.pending} dependencies still need evidence. Conversion waits for the required files and bindings.</p>}{!model.markdown?.artifact&&<p className="fine-print">Save the process instructions before copying a current assistant prompt.</p>}<GuideWorkspaceSummary model={model} disabled={blocked} onSave={()=>void mutate('save')}/></section>{model.handoffs.copilot&&<GuidePrompt role="Copilot" handoff={model.handoffs.copilot} disabled={blocked||!model.markdown?.artifact} onCopy={()=>void copy('Copilot')}/>} {model.handoffs.claude&&<GuidePrompt role="Claude" handoff={model.handoffs.claude} disabled={blocked||!model.markdown?.artifact} onCopy={()=>void copy('Claude')}/>}</>}
  {model&&guideMatchesProcess(model,processId)&&<GuideCurrentPanel current={!!current} disabled={disabled||working||uncertain}>{renderPanel(model,savedRequirements)}</GuideCurrentPanel>}
  {feedback&&<p role="status" className="guide-feedback">{feedback}</p>}{actionError&&<div className="error" role="alert"><p>{actionError}</p>{uncertain&&<p>The request may have reached the Coordinator. Read the current guide before trying another action.</p>}</div>}
 </div>;
}
