import React,{useEffect,useRef,useState} from 'react';

type Utility={id:string;name:string;aliases:string[];category:string;behavior:string;required_evidence:string[];risks:string[];references:string[];owner?:string;version?:string;record_formats?:string[];return_codes?:string[];side_effects?:string[];dependencies?:string[]};
type Snapshot={schema_version:number;catalog:{reviewed_on:string;categories:{kind:string;description:string;required_evidence:string[]}[];utilities:Utility[];topics:{id:string;title:string;checks:string[];references:string[]}[]};application:{application:string;utilities:Utility[];notes:string[]};source_hashes:{standard:string;application:string|null};content_hash:string};
type KnowledgeResponse={snapshot:Snapshot;application_template_path:string;application_path:string;reference_path:string};
type Classification={kind:string;confidence:string;candidate_kinds?:string[];evidence:{line:number|null;reason:string}[];evidence_truncated?:boolean;conflicts:string[];utility_ids:string[];conversion_support:string};
type Finding={job:string;step:string;program:string;utility_id:string;behavior:string;required_evidence:string[];risks:string[];conversion_support:string;source:string};
type ProcessKnowledge={id:string;artifacts:string[];mainframe_knowledge?:Snapshot;analysis?:{classifications?:Record<string,Classification>;utility_findings?:Finding[]}};

function TextList({items}:{items?:string[]}){
 return items?.length?<ul className="compact-list">{items.map((value,i)=><li key={i}>{value}</li>)}</ul>:<p>No entries recorded.</p>;
}

export function KnowledgePanel({process}:{process?:ProcessKnowledge}){
 const [response,setResponse]=useState<KnowledgeResponse|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[revision,setRevision]=useState(0),[query,setQuery]=useState(''),[scope,setScope]=useState<'current'|'process'>(()=>process?.mainframe_knowledge?'process':'current');
 useEffect(()=>{let active=true;setLoading(true);setError('');fetch('/api/knowledge').then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error||'Knowledge catalog unavailable');if(!d.snapshot?.catalog||!d.snapshot?.application)throw Error('Knowledge catalog returned an unexpected response');if(active)setResponse(d);}).catch(e=>{if(active){setError(String(e));setResponse(null);}}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[revision]);
 useEffect(()=>{setScope(process?.mainframe_knowledge?'process':'current');setQuery('');},[process?.id,process?.mainframe_knowledge?.content_hash]);
 const searchField=useRef<HTMLInputElement>(null);
 const frozen=process?.mainframe_knowledge;
 const snapshot=scope==='process'?frozen:response?.snapshot;
 const classifications=Object.entries(process?.analysis?.classifications||{});
 const findings=process?.analysis?.utility_findings||[];
 const utilities=snapshot?[...snapshot.catalog.utilities.map(u=>({...u,source:'Standard reference'})),...snapshot.application.utilities.map(u=>({...u,source:'Application knowledge'}))].filter(u=>`${u.name} ${u.id} ${u.aliases.join(' ')} ${u.category} ${u.behavior}`.toLowerCase().includes(query.toLowerCase())):[];
 return <>
 <section><div className="sectionhead"><h2>Mainframe knowledge you can inspect</h2><button disabled={loading} onClick={()=>setRevision(x=>x+1)}>{loading?'Loading…':'Reload current catalog'}</button></div>
 <p>The catalog describes file types, standard utilities and application-specific behavior. Recognizing a file or utility does not prove that its behavior has been converted. Executable support and verification remain separate gates.</p>
 {error&&<div role="alert" className="error"><p>{error}</p><p>Check <code>knowledge/application-knowledge.json</code> in your workspace against <code>examples/application-knowledge.json</code>, then reload. The standard reference is <code>knowledge/mainframe-catalog.json</code> in the application repository. Existing process snapshots remain separate.</p></div>}
 {loading&&!response&&<p role="status">Loading the validated local catalog…</p>}
 {response&&<div className="knowledge-paths"><h3>Add your application knowledge before starting a process</h3><p>Copy the template if the application file does not exist, then edit the application file in your workspace. Record utility aliases, behavior, input and output evidence, record formats, return codes, side effects, dependencies and the responsible owner. Keep credentials and raw production records out of the catalog.</p><dl><dt>Application file to edit</dt><dd><code>{response.application_path}</code></dd><dt>Template to copy</dt><dd><code>{response.application_template_path}</code></dd><dt>Field guide and mainframe reference</dt><dd><code>{response.reference_path}</code></dd></dl><p>Reload validates your edits. Each new process freezes its own catalog snapshot. Editing the current file does not change an existing process or grant conversion credit.</p></div>}
 <label>Catalog to browse<select value={scope} onChange={e=>setScope(e.target.value as 'current'|'process')}><option value="current">Current catalog for new processes</option><option value="process" disabled={!frozen}>Selected process: frozen catalog</option></select></label>
 {snapshot&&<><p><strong>{scope==='process'?'Frozen process reference':'Current reference'}</strong> · reviewed {snapshot.catalog.reviewed_on} · application: {snapshot.application.application||'No application name supplied'}</p><details><summary>Catalog fingerprints</summary><p>Snapshot: <code>{snapshot.content_hash}</code></p><p>Standard file: <code>{snapshot.source_hashes.standard}</code></p><p>Application file: <code>{snapshot.source_hashes.application||'No application overlay supplied'}</code></p></details>
 <h3>Utilities and wrappers</h3><label htmlFor="knowledge-utility-search">Find a utility<input id="knowledge-utility-search" ref={searchField} type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name, alias, category or behavior"/></label>{query&&<button type="button" aria-label="Clear utility search" onClick={()=>{setQuery('');searchField.current?.focus();}}>Clear search</button>}<p role="status">{utilities.length} utilities match. These entries describe behavior; they do not install or enable a converter.</p>
 <div className="knowledge-list">{utilities.map(u=><details key={`${u.source}:${u.id}`}><summary>{u.name} <span className="muted">· {u.source} · {u.category}</span></summary><p>{u.behavior}</p><p><strong>Aliases:</strong> {u.aliases.join(', ')||'None recorded'}</p>{(u.owner||u.version)&&<p><strong>Owner:</strong> {u.owner||'Unspecified'} · <strong>Version:</strong> {u.version||'Unspecified'}</p>}<h4>Evidence needed</h4><TextList items={u.required_evidence}/><h4>Behavior that must be accounted for</h4><TextList items={u.risks}/>{[['Record formats',u.record_formats],['Return codes',u.return_codes],['Side effects',u.side_effects],['Dependencies',u.dependencies]].map(([label,values])=>Array.isArray(values)&&values.length?<div key={String(label)}><h4>{label}</h4><TextList items={values}/></div>:null)}{u.references.length>0&&<><h4>References</h4><TextList items={u.references}/></>}</details>)}</div>
 <details className="knowledge-section"><summary>Recognized file categories ({snapshot.catalog.categories.length})</summary><div className="table-scroll" role="region" aria-label="Recognized file categories" tabIndex={0}><table><thead><tr><th scope="col">Category</th><th scope="col">Meaning</th><th scope="col">Required evidence</th></tr></thead><tbody>{snapshot.catalog.categories.map(c=><tr key={c.kind}><td>{c.kind.replaceAll('_',' ')}</td><td>{c.description}</td><td><TextList items={c.required_evidence}/></td></tr>)}</tbody></table></div></details>
 <details className="knowledge-section"><summary>Mainframe behavior checklist ({snapshot.catalog.topics.length} topics)</summary>{snapshot.catalog.topics.map(topic=><div key={topic.id}><h4>{topic.title}</h4><TextList items={topic.checks}/>{topic.references.length>0&&<details><summary>References</summary><TextList items={topic.references}/></details>}</div>)}</details>
 {snapshot.application.notes.length>0&&<details className="knowledge-section"><summary>Application notes</summary><TextList items={snapshot.application.notes}/></details>}</>}
 </section>
 <section><h2>How this process was classified</h2>{!process?<p>Select a process to see the file evidence and its frozen mainframe reference.</p>:<>
 {!frozen&&<p className="blocker">This process has no frozen mainframe knowledge snapshot. An older run may not contain classification evidence. Its existing results are not retroactively classified by the current catalog.</p>}
 {process.artifacts.includes('analysis/mainframe-knowledge.json')&&<a className="download" href={`/api/process/${process.id}/artifact?path=${encodeURIComponent('analysis/mainframe-knowledge.json')}`}>Download this process’s frozen mainframe knowledge</a>}
 {!classifications.length?<p>No classification evidence is available for this process yet. Start analysis to create it for a new process; historical runs may predate classification.</p>:<><p>Classification uses the supplied source evidence and catalog context. Conflicts, unfamiliar members and utility behavior requiring an adapter remain visible. Use Source coverage for the actual source-to-target disposition and proof.</p><div className="table-scroll" role="region" aria-label="Source classification evidence" tabIndex={0}><table><thead><tr><th scope="col">Source file</th><th scope="col">Classification</th><th scope="col">Evidence and conflicts</th><th scope="col">Conversion support</th></tr></thead><tbody>{classifications.map(([path,c])=><tr key={path}><td><code>{path}</code></td><td>{c.kind.replaceAll('_',' ')}<br/><small>Confidence: {c.confidence}</small>{c.utility_ids.length>0&&<p>Utilities: {c.utility_ids.join(', ')}</p>}</td><td><TextList items={c.evidence.map(e=>e.line===null?e.reason:`Line ${e.line}: ${e.reason}`)}/>{c.evidence_truncated&&<p>Evidence display is bounded; inspect the original source for the complete file.</p>}{c.conflicts.length>0&&<div className="blocker"><strong>Conflicting evidence</strong><TextList items={c.conflicts}/></div>}</td><td>{c.conversion_support==='not_established'?'Recognition only; conversion support is not established.':c.conversion_support.replaceAll('_',' ')}</td></tr>)}</tbody></table></div></>}
 {findings.length>0&&<><h3>Utility steps requiring explicit handling</h3>{findings.map((f,i)=><details className="knowledge-section" key={`${f.job}:${f.step}:${i}`}><summary>{f.job} / {f.step} · {f.program}</summary><p>{f.behavior}</p><p><strong>Reference:</strong> {f.utility_id} ({f.source}) · <strong>Conversion:</strong> {f.conversion_support.replaceAll('_',' ')}</p><h4>Required evidence</h4><TextList items={f.required_evidence}/><h4>Risks to account for</h4><TextList items={f.risks}/></details>)}</>}
 </>}</section></>;
}
