import React,{useEffect,useId,useState} from 'react';

export type InventoryBaseline={declared_total:number;status:string;provenance:string;categories:{key:string;label:string;count:number}[];application_locations?:{name:string;role:string;status:string}[]};
type AssetCount={kind:string;label:string;count:number|string;observed_count:number;status:string;basis:string;gaps:number};
type Node={id:string;name:string;kind:string;path?:string|null;selected:boolean;resolution:string};
type Edge={source:string;target:string;kind:string;resolution:string};
export type Lineage={nodes:Node[];edges:Edge[];scope:{root_jobs:string[];selected_file_count:number;original_file_count:number;discovered_file_count?:number;retained_file_count?:number};closure:{status:string;complete:boolean;gaps:{kind:string;name:string;reason:string;status:string}[];input_data_readiness:string};process_assets:AssetCount[];application_input_locations?:{name:string;availability:string;readiness:string}[]};

export function EstateInventory({baseline,lineage}:{baseline?:InventoryBaseline|null;lineage?:Lineage|null}){
 if(!baseline)return <p className="notice">The declared application inventory has not been loaded.</p>;
 const total=baseline.categories.reduce((sum,item)=>sum+item.count,0),counts=new Map((lineage?.process_assets||[]).map(item=>[item.kind,item]));
 return <section className="inventory-card"><p className="eyebrow">APPLICATION INVENTORY</p><h2>Declared estate and selected process</h2><p>Declared total: <strong>{baseline.declared_total.toLocaleString()}</strong> · Category sum: <strong>{total.toLocaleString()}</strong> · Unreconciled: <strong>{(baseline.declared_total-total).toLocaleString()}</strong>.</p><p className="fine-print">{baseline.provenance}. These declarations do not establish source presence, conversion or complete application coverage.</p><div className="table-scroll" role="region" aria-label="Declared and observed inventory" tabIndex={0}><table><caption className="sr-only">Declared inventory and source-backed process counts</caption><thead><tr><th scope="col">Asset category</th><th scope="col">Declared baseline</th><th scope="col">Selected process scope</th><th scope="col">Static observations</th></tr></thead><tbody>{baseline.categories.map(item=>{const found=counts.get(item.key);return <tr key={item.key}><th scope="row">{item.label}</th><td>{item.count.toLocaleString()}<br/><small>User reported · unverified</small></td><td>{found?.count??'Unknown'}<br/><small>{found?found.status.replaceAll('_',' ').toLowerCase():'Lineage not mapped'}</small></td><td>{found?`${found.observed_count} found; ${found.gaps} gaps`:'Unknown'}</td></tr>;})}</tbody></table></div>{baseline.application_locations?.length?<p className="fine-print">{baseline.application_locations.map(location=>location.name).join(' and ')} are application staging / availability locations. Dataset names, availability and input readiness remain Unknown until actual evidence establishes them.</p>:null}</section>;
}

export function LineageGraph({lineage}:{lineage:Lineage}){
 const [expanded,setExpanded]=useState(false),marker=useId().replaceAll(':','');
 const selected=lineage.nodes.filter(node=>node.selected&&node.kind!=='source_file');
 const roots=selected.filter(node=>node.kind==='job'&&lineage.scope.root_jobs.some(name=>name.toUpperCase()===node.name.toUpperCase()));
 const ranks=new Map<string,number>(roots.map(node=>[node.id,0])),adjacent=new Map<string,Edge[]>();
 for(const edge of lineage.edges){if(!adjacent.has(edge.source))adjacent.set(edge.source,[]);adjacent.get(edge.source)!.push(edge);}
 const queue=roots.map(node=>node.id);
 for(let index=0;index<queue.length;index++)for(const edge of adjacent.get(queue[index])||[]){if(!ranks.has(edge.target)){ranks.set(edge.target,Math.min(4,(ranks.get(edge.source)||0)+1));queue.push(edge.target);}}
 const order=new Map(queue.map((id,index)=>[id,index])),limit=expanded?56:28;
 const visible=[...selected].sort((a,b)=>(order.get(a.id)??Number.MAX_SAFE_INTEGER)-(order.get(b.id)??Number.MAX_SAFE_INTEGER)||a.id.localeCompare(b.id)).slice(0,limit);
 const rows=[0,0,0,0,0],positions=new Map(visible.map(node=>{const column=ranks.get(node.id)??4;return [node.id,{x:column*205+12,y:rows[column]++*78+12}];}));
 const height=Math.max(120,...rows.map(row=>row*78+20)),edges=lineage.edges.filter(edge=>positions.has(edge.source)&&positions.has(edge.target));
 if(!visible.length)return <p className="notice">No source-backed job graph is available yet. Inspect the named closure gaps.</p>;
 return <><div className="lineage-graph-scroll" role="region" aria-label="Selected-job dependency graph" tabIndex={0}><svg viewBox={`0 0 1025 ${height}`} width="1025" height={height} role="img" aria-label="Selected-job dependency graph"><title>Selected-job dependency graph</title><desc>Recorded nodes and relationships from frozen source. Showing {visible.length} of {selected.length} selected objects. Missing references do not establish executable support.</desc><defs><marker id={marker} markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8" fill="currentColor"/></marker></defs>{edges.map((edge,index)=>{const from=positions.get(edge.source)!,to=positions.get(edge.target)!;return <path key={`${edge.source}-${edge.target}-${index}`} className={edge.resolution==='resolved'?'graph-edge':'graph-edge unresolved'} d={`M ${from.x+178} ${from.y+28} C ${from.x+195} ${from.y+28}, ${to.x-18} ${to.y+28}, ${to.x} ${to.y+28}`} fill="none" markerEnd={`url(#${marker})`}><title>{`${edge.kind.replaceAll('_',' ')} · ${edge.resolution}`}</title></path>;})}{visible.map(node=>{const position=positions.get(node.id)!;return <g key={node.id} transform={`translate(${position.x},${position.y})`} className={['local_source','read_only_metadata','manifest_context'].includes(node.resolution)?'graph-node':'graph-node unresolved'}><title>{`${node.name} · ${node.kind} · ${node.resolution}${node.path?` · ${node.path}`:''}`}</title><rect width="178" height="56" rx="6"/><text x="10" y="20">{node.name.length>22?node.name.slice(0,21)+'…':node.name}</text><text className="graph-kind" x="10" y="39">{node.kind.replaceAll('_',' ')}</text></g>;})}</svg></div><p className="fine-print">Showing {visible.length} of {selected.length} selected objects and {edges.length} recorded links. The full frozen graph is available below; static closure is separate from conversion and input data readiness.</p>{selected.length>28&&<button onClick={()=>setExpanded(value=>!value)}>{expanded?'Show fewer graph nodes':'Show more graph nodes'}</button>}</>;
}

export function LineagePanel({process,baseline}:{process:{id:string;status:string;lineage?:Lineage|null};baseline?:InventoryBaseline|null}){
 const [loaded,setLoaded]=useState<{id:string;data:Lineage}|null>(null),[error,setError]=useState(''),[revision,setRevision]=useState(0),[loading,setLoading]=useState(false);
 const supplied=process.lineage?.nodes?process.lineage:null,lineage=supplied||(loaded?.id===process.id?loaded.data:null);
 useEffect(()=>{
  const controller=new AbortController();setError('');
  if(supplied||['READY','QUEUED_ANALYSIS'].includes(process.status)){setLoading(false);return ()=>controller.abort();}
  setLoading(true);fetch(`/api/process/${encodeURIComponent(process.id)}/agent/lineage`,{signal:controller.signal}).then(async response=>{const data=await response.json();if(!response.ok)throw Error(data.error||data.detail||'Lineage is not available yet.');if(!Array.isArray(data.nodes)||!Array.isArray(data.edges)||!Array.isArray(data.process_assets))throw Error('Unexpected lineage response.');if(!controller.signal.aborted)setLoaded({id:process.id,data});}).catch(failure=>{if(!controller.signal.aborted)setError(failure instanceof Error?failure.message:'Lineage could not be loaded.');}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});
  return ()=>controller.abort();
 },[process.id,process.status,!!supplied,revision]);
 return <><section className="lineage-card"><div className="sectionhead"><div><p className="eyebrow">FIRST GATE · SELECTED-JOB LINEAGE</p><h2>Map dependencies before conversion</h2></div>{lineage&&<span className={`status-pill ${lineage.closure.complete?'':'blocked'}`}>{lineage.closure.status}</span>}</div><p>Local repository evidence is checked first. Missing selected-job dependencies may use approved read-only Zowe or Db2 lookup; original exports remain preserved.</p>{loading&&<p role="status">Loading frozen lineage…</p>}{error&&<div className="error" role="alert"><p>{error}</p><button onClick={()=>setRevision(value=>value+1)}>Retry loading lineage</button></div>}{lineage?<><p><strong>{lineage.scope.selected_file_count}</strong> selected source files · <strong>{lineage.scope.original_file_count}</strong> original export files · <strong>{lineage.scope.discovered_file_count??'Unknown'}</strong> discovered source files · <strong>{lineage.scope.retained_file_count??'Unknown'}</strong> total retained source files · <strong>{lineage.closure.gaps.length}</strong> closure gaps · Input data readiness: <strong>{lineage.closure.input_data_readiness||'Unknown'}</strong>.</p><LineageGraph lineage={lineage}/><a className="download" href={`/api/process/${encodeURIComponent(process.id)}/agent/lineage`} target="_blank" rel="noreferrer">Inspect complete frozen lineage JSON<span className="sr-only"> (opens in a new tab)</span></a>{lineage.closure.gaps.length>0&&<details><summary>Named discovery gaps ({lineage.closure.gaps.length})</summary><ul className="compact-list">{lineage.closure.gaps.slice(0,100).map((gap,index)=><li key={`${gap.kind}-${gap.name}-${index}`}><strong>{gap.kind}: {gap.name}</strong> · {gap.reason}</li>)}</ul>{lineage.closure.gaps.length>100&&<p>Showing the first 100 gaps. The complete list remains in frozen lineage JSON.</p>}</details>}</>:!loading&&!error&&<p className="notice">Start analysis to map the selected job closure. No closure or conversion credit has been recorded yet.</p>}</section><EstateInventory baseline={baseline} lineage={lineage}/></>;
}
