import {PendingTransaction,callOnline,OnlineHttpError} from './onlineRequest';
import {onlineDefaults,onlineRecord,stringifyOnlineJSON,type OnlineField} from './onlineJson';
import React,{useState,useRef} from 'react';
import {createRoot} from 'react-dom/client';

export function OnlineFields({fields,values,disabled,onChange}:{fields:Record<string,OnlineField>;values:Record<string,string>;disabled:boolean;onChange:(name:string,value:string)=>void}){
 return <>{Object.entries(fields).map(([name,field])=><p key={name}><label htmlFor={'record-'+name}>{name}</label><input id={'record-'+name} required disabled={disabled} inputMode={field.type==='integer'?'numeric':'text'} maxLength={field.type==='integer'?256:field.width*2} aria-describedby={'record-help-'+name} value={values[name]??''} onChange={e=>onChange(name,e.target.value)}/><small id={'record-help-'+name}>{field.type==='integer'?String(field.min??0)+'–'+String(field.max)+' · whole number':field.width+' characters, including spaces'}</small></p>)}</>;
}
export function OnlineResult({output}:{output:any}){
 return <section aria-live="polite"><h2>Result</h2><pre>{stringifyOnlineJSON(output.record,2,1024*1024)}</pre><p>Return code: {String(output.return_code)}</p></section>;
}
export function Online(){
 const pending=useRef(new PendingTransaction()),locked=useRef(false);
 const [token,setToken]=useState(''),[contracts,setContracts]=useState<any>({}),[tx,setTx]=useState(''),[values,setValues]=useState<Record<string,string>>({}),[session,setSession]=useState<any>(null),[output,setOutput]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const uncertain=!!pending.current.attempt;
 async function connect(){if(locked.current)return;locked.current=true;setBusy(true);setError('');try{const data=await callOnline('/api/contracts',token),first=Object.keys(data)[0]||'';const defaults=first?onlineDefaults(data[first].fields):{};setContracts(data);setTx(first);setValues(defaults);setSession(null);setOutput(null);}catch(e){setError(String(e));}finally{locked.current=false;setBusy(false);}}
 async function submit(event:React.FormEvent){event.preventDefault();if(locked.current)return;locked.current=true;setBusy(true);setError('');try{
  if(!pending.current.attempt){const record=onlineRecord(contracts[tx].fields,values);const current=session||await callOnline('/api/sessions',token,{body:{transaction:tx}});setSession(current);pending.current.prepare(tx,current,record);}
  const attempt=pending.current.attempt!;const result=await callOnline('/api/transactions/'+encodeURIComponent(attempt.transaction),token,{serializedBody:attempt.serializedBody,headers:{'X-Session-ID':attempt.session.session_id,'Idempotency-Key':attempt.key}});setSession({...attempt.session,revision:result.revision});setOutput(result.result);pending.current.clear();
 }catch(e){if(e instanceof OnlineHttpError)pending.current.received(e.status);setError(String(e)+(pending.current.attempt?' — Retry resends the same pending request.':''));}finally{locked.current=false;setBusy(false);}}
 async function endSession(){if(locked.current)return;locked.current=true;setBusy(true);setError('');try{
  if(session){try{await callOnline('/api/sessions/'+encodeURIComponent(session.session_id),token,{method:'DELETE'});}catch(e){if(!(e instanceof OnlineHttpError)||![404,410].includes(e.status))throw e;}}
  pending.current.clear();setSession(null);setOutput(null);
 }catch(e){setError(String(e)+' — The pending session is retained. Try ending it again.');}finally{locked.current=false;setBusy(false);}}
 return <main className="online-pilot" aria-busy={busy}><style>{`.online-pilot{max-width:760px;margin:2rem auto;padding:1rem;font-family:system-ui;line-height:1.5;color:#242424}.online-pilot *{box-sizing:border-box}.online-pilot h1{font-size:clamp(1.5rem,5vw,2rem)}.online-pilot label,.online-pilot small{display:block;overflow-wrap:anywhere}.online-pilot input,.online-pilot select,.online-pilot button{font:inherit;min-height:44px;max-width:100%;margin:6px 0;padding:8px}.online-pilot input,.online-pilot select{width:100%}.online-pilot button{margin-right:8px;cursor:pointer}.online-pilot :focus-visible{outline:3px solid #1763aa;outline-offset:3px}.online-pilot pre{white-space:pre-wrap;overflow-wrap:anywhere}.online-pilot [role=alert]{overflow-wrap:anywhere}.online-pilot small{color:#555}`}</style><h1>Business transaction pilot</h1><p>Source-derived record service. This form does not claim to replace a CICS/BMS screen or its session behavior.</p><label htmlFor="online-token">Local access token</label><input id="online-token" type="password" autoComplete="off" disabled={busy||uncertain} value={token} onChange={e=>{setToken(e.target.value);setContracts({});setSession(null);setOutput(null);}}/><button disabled={busy||!token||uncertain} onClick={()=>void connect()}>Connect</button>{error&&<p role="alert">{error}</p>}{Object.keys(contracts).length>0&&<><label htmlFor="online-transaction">Transaction</label><select id="online-transaction" disabled={busy||uncertain} value={tx} onChange={e=>{const next=e.target.value;setTx(next);setSession(null);setValues(onlineDefaults(contracts[next].fields));setOutput(null);setError('');}}>{Object.keys(contracts).map(id=><option key={id}>{id}</option>)}</select><form onSubmit={submit}><OnlineFields fields={contracts[tx]?.fields||{}} values={values} disabled={busy||uncertain} onChange={(name,value)=>setValues({...values,[name]:value})}/><button disabled={busy}>{busy?'Processing…':uncertain?'Retry pending transaction':'Run transaction'}</button><button type="button" disabled={busy||!session} onClick={()=>void endSession()}>End session</button></form></>}{output&&<OnlineResult output={output}/>}</main>;
}
if(typeof document!=='undefined'){const root=document.getElementById('root');if(root)createRoot(root).render(<Online/>);}
