import {PendingTransaction} from './onlineRequest';
import React,{useState,useRef} from 'react';
import {createRoot} from 'react-dom/client';
class HttpError extends Error {constructor(public status:number,message:string){super(message);}}
function Online(){
 const pending=useRef(new PendingTransaction());
 const [token,setToken]=useState(''),[contracts,setContracts]=useState<any>({}),[tx,setTx]=useState(''),[values,setValues]=useState<Record<string,string>>({}),[session,setSession]=useState<any>(null),[output,setOutput]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function call(path:string,body?:any,headers:any={},method?:string){const response=await fetch(path,{method:method||(body?'POST':'GET'),headers:{Authorization:'Bearer '+token,'Content-Type':'application/json',...headers},body:body?JSON.stringify(body):undefined});const data=await response.json();if(!response.ok)throw new HttpError(response.status,typeof data.detail==='string'?data.detail:JSON.stringify(data.detail));return data;}
 async function connect(){setBusy(true);setError('');try{const data=await call('/api/contracts');setContracts(data);setTx(Object.keys(data)[0]||'');setValues({});setSession(null);}catch(e){setError(String(e));}finally{setBusy(false);}}
 async function submit(event:React.FormEvent){event.preventDefault();setBusy(true);setError('');try{
  if(!pending.current.attempt){const current=session||await call('/api/sessions',{transaction:tx});setSession(current);const record=Object.fromEntries(Object.entries(contracts[tx].fields).map(([name,field]:any)=>[name,field.type==='integer'?(values[name]?.trim()?Number(values[name]):null):(values[name]??'')]));pending.current.prepare(tx,current,record);}
  const attempt=pending.current.attempt!;const result=await call('/api/transactions/'+encodeURIComponent(attempt.transaction),attempt.body,{'X-Session-ID':attempt.session.session_id,'Idempotency-Key':attempt.key});setSession({...attempt.session,revision:result.revision});setOutput(result.result);pending.current.clear();
 }catch(e){if(e instanceof HttpError)pending.current.received(e.status);setError(String(e)+(pending.current.attempt?' — Retry resends the same pending request.':''));}finally{setBusy(false);}}

 return <main style={{maxWidth:760,margin:'2rem auto',padding:'1rem',fontFamily:'system-ui'}}><h1>Business transaction pilot</h1><p>Source-derived record service. This form does not claim to replace a CICS/BMS screen or its session behavior.</p><label>Local access token <input type="password" autoComplete="off" disabled={busy} value={token} onChange={e=>{pending.current.clear();setToken(e.target.value);setContracts({});setSession(null);}}/></label> <button disabled={busy||!token||!!pending.current.attempt} onClick={connect}>Connect</button>{error&&<p role="alert">{error}</p>}{Object.keys(contracts).length>0&&<><label>Transaction <select disabled={busy||!!pending.current.attempt} value={tx} onChange={e=>{pending.current.clear();setTx(e.target.value);setSession(null);setValues({});setOutput(null);}}>{Object.keys(contracts).map(id=><option key={id}>{id}</option>)}</select></label><form onSubmit={submit}>{Object.entries(contracts[tx]?.fields||{}).map(([name,field]:any)=><p key={name}><label>{name} ({field.type==='integer'?'0–'+field.max:field.width+' characters, including spaces'}) <input required disabled={busy||!!pending.current.attempt} inputMode={field.type==='integer'?'numeric':'text'} value={values[name]??''} onChange={e=>setValues({...values,[name]:e.target.value})}/></label></p>)}<button disabled={busy}>{busy?'Processing…':'Run transaction'}</button> <button type="button" disabled={busy} onClick={async()=>{if(session){try{await call('/api/sessions/'+session.session_id,undefined,{},'DELETE');}catch(e){setError(String(e));}}pending.current.clear();setSession(null);setOutput(null);}}>End session</button></form></>}{output&&<section aria-live="polite"><h2>Result</h2><pre style={{whiteSpace:'pre-wrap'}}>{JSON.stringify(output.record,null,2)}</pre><p>Return code: {output.return_code}</p></section>}</main>;
}
createRoot(document.getElementById('root')!).render(<Online/>);
