import React,{useEffect,useState} from 'react';

type SourceRef={path:string;source_hash:string;start_line:number|null;end_line:number|null};
type Rule={id:string;description:string;category:string;selection:string;status:string;reason:string;evidence:SourceRef};
type Program={id:string;name:string;scope:string;source:SourceRef;functional_summary:string;analysis_state:string;entrypoints:{kind:string;label:string;entry_program:string}[];entrypoints_complete:boolean;entrypoint_count:number;rules:Rule[];rules_complete:boolean;rule_counts:{identified:number|null;selected:number|null;excluded:number|null;converted_verified:number|null};technical_spec:{fields:{name:string;type?:string;width?:number;length?:number;group?:string;storage_section?:string;source_ref?:string}[];field_count:number;fields_complete:boolean;dependencies:{path?:string;name?:string;kind?:string}[];dependency_count:number;dependencies_complete:boolean;links:{kind:string;target:string;resolution?:string}[];link_count:number;links_complete:boolean;io_status:string};risks:{kind?:string;message?:string}[];risk_count:number;risks_complete:boolean;validation_requirements:string[];personas:Record<string,string>};
export type InsightsView={basis:string;boundary:string;program_total:number|null;after:number;next_after:number;has_more:boolean;page_size:number;programs:Program[];verification_basis:string;inventory:{retained_files:number|null;selected_files:number|null;estate_total:null;basis:string;categories:{kind:string;label:string;file_count:number|null;selected_file_count:number|null;definition_count:number|null;evidence:{path:string;source_hash:string;selected:boolean;evidence:{line:number|null;reason:string}[]}[];evidence_complete:boolean}[];unresolved_count:number;unresolved_classifications:{path:string;source_hash:string}[];unresolved_complete:boolean;sql_procedures:{observed_definitions:number|null;estate_total:null;basis:string;evidence:(SourceRef&{name:string})[];evidence_complete:boolean}}};
const count=(value:number|null)=>value===null?'Unknown':value;

/** Documentation is an evidence projection; it cannot change conversion scope. */
export function ProgramKnowledge({view,onPage,busy=false}:{view:InsightsView;onPage?:(cursor:number)=>void;busy?:boolean}){
 const [programId,setProgramId]=useState(view.programs[0]?.id||'');
 useEffect(()=>setProgramId(view.programs[0]?.id||''),[view.after,view.programs[0]?.id]);
 const program=view.programs.find(item=>item.id===programId)||view.programs[0];
 const inventory=view.inventory;
 return <div className="run-summary">
  <h3>Application inventory and program knowledge</h3>
  <p>{view.boundary}</p>
  <dl className="usage-grid"><div><dt>Retained source files</dt><dd>{count(inventory.retained_files)}</dd></div><div><dt>Files in this process</dt><dd>{count(inventory.selected_files)}</dd></div><div><dt>Observed COBOL definitions</dt><dd>{count(view.program_total)}</dd></div><div><dt>Entire application estate</dt><dd>Unknown</dd></div></dl>
  <details><summary>Source types, screens and Db2 procedures</summary><p>{inventory.basis}</p>
   <div className="table-scroll"><table><caption>Retained export breakdown</caption><thead><tr><th scope="col">Source type</th><th scope="col">Files</th><th scope="col">Selected files</th><th scope="col">Observed definitions</th></tr></thead><tbody>{inventory.categories.map(row=><tr key={row.kind}><th scope="row">{row.label}</th><td>{count(row.file_count)}</td><td>{count(row.selected_file_count)}</td><td>{row.definition_count===null?'Not counted':row.definition_count}</td></tr>)}</tbody></table></div>
   <p><strong>{count(inventory.sql_procedures.observed_definitions)} observed Db2 procedure definitions</strong>. {inventory.sql_procedures.basis}</p>
   <ul className="compact-list">{inventory.sql_procedures.evidence.map((item,index)=><li key={`${item.path}:${item.start_line}:${index}`}><strong>{item.name}</strong> · {item.path}:{item.start_line}–{item.end_line}<p><code>SHA256 {item.source_hash}</code></p></li>)}</ul>
   {!inventory.sql_procedures.evidence_complete&&<p>Procedure references are truncated; the complete retained source remains in the coverage report.</p>}
   {inventory.unresolved_count>0&&<p>{inventory.unresolved_count} files have unknown or conflicting classifications. They remain visible obligations.</p>}
   <details><summary>Classification evidence</summary>{inventory.categories.filter(row=>row.evidence.length>0).map(row=><div key={row.kind}><h4>{row.label}</h4>{row.evidence.map(item=><p key={item.path}><strong>{item.path}</strong> · {item.selected?'In process':'Outside process'}<br/>{item.evidence.map(e=>`${e.line===null?'File':`Line ${e.line}`}: ${e.reason}`).join('; ')}<br/><code>SHA256 {item.source_hash}</code></p>)}{!row.evidence_complete&&<p>Showing {row.evidence.length} of {row.file_count} file references.</p>}</div>)}</details>
  </details>
  <details><summary>Program documentation ({count(view.program_total)})</summary>
   <p>Technical entrypoints map jobs and transactions to programs. Business use cases and business intent require validation.</p>
   {view.program_total===null?<p>Source analysis is not available yet.</p>:view.program_total===0?<p>No COBOL program declarations were recognized in this retained export. This does not prove the application has no programs.</p>:<>
    <label htmlFor="program-knowledge-selection">Choose a program on this page</label><select id="program-knowledge-selection" value={program?.id||''} onChange={event=>setProgramId(event.target.value)}>{view.programs.map(item=><option key={item.id} value={item.id}>{item.name} · {item.source.path}</option>)}</select>
    <p>Showing {view.after+1}–{view.next_after} of {view.program_total} definitions.</p>
    {onPage&&<><button disabled={busy||view.after===0} onClick={()=>onPage(Math.max(0,view.after-view.page_size))}>Previous programs</button> <button disabled={busy||!view.has_more} onClick={()=>onPage(view.next_after)}>Next programs</button></>}
   </>}
   {program&&<article><h4>{program.name} · {program.scope==='SELECTED_PROCESS'?'In selected process':'Outside selected process'}</h4><p>{program.functional_summary}</p><p>{program.source.path}:{program.source.start_line}–{program.source.end_line}<br/><code>SHA256 {program.source.source_hash}</code></p>
    <dl className="usage-grid"><div><dt>Identified rules</dt><dd>{count(program.rule_counts.identified)}</dd></div><div><dt>Selected Yes</dt><dd>{count(program.rule_counts.selected)}</dd></div><div><dt>Selected No</dt><dd>{count(program.rule_counts.excluded)}</dd></div><div><dt>Verified by replayed coverage</dt><dd>{count(program.rule_counts.converted_verified)}</dd></div></dl>
    {view.verification_basis==='NOT_REPLAYED'&&<p>Live documentation does not replay target verification. Use the accepted rule and coverage reports for verified conversion counts.</p>}
    <h4>Use-case entry mappings</h4>{program.entrypoints.length===0?<p>No entry mapping is evidenced in this view.</p>:<ul className="compact-list">{program.entrypoints.map((item,index)=><li key={`${item.kind}:${item.label}:${index}`}>{item.label} → {item.entry_program} ({item.kind.replaceAll('_',' ')})</li>)}</ul>}{!program.entrypoints_complete&&<p>Showing {program.entrypoints.length} of {program.entrypoint_count} mappings.</p>}
    <h4>Functional rules and requirements</h4><p>Default Yes requests conversion. Only an explicit scope Save records the selection; it is separate from the one human SME return.</p>
    <div className="table-scroll"><table><caption>Source-derived rule observations</caption><thead><tr><th scope="col">Behavior</th><th scope="col">Classification</th><th scope="col">Selection</th><th scope="col">Evidence and status</th></tr></thead><tbody>{program.rules.map(rule=><tr key={rule.id}><td>{rule.description}</td><td>{rule.category.replaceAll('_',' ')}</td><td>{rule.selection}</td><td>Lines {rule.evidence.start_line}–{rule.evidence.end_line} · {rule.status.replaceAll('_',' ')}<p>{rule.reason}</p></td></tr>)}</tbody></table></div>
    {!program.rules_complete&&<p>Showing {program.rules.length} of {program.rule_counts.identified} rules. Full rules are available in Requirements and Rules &amp; lineage.</p>}
    <details><summary>Technical specification and validation requirements</summary><p>{program.technical_spec.io_status}</p><h4>Parsed fields ({program.technical_spec.field_count})</h4><ul className="compact-list">{program.technical_spec.fields.map(field=><li key={field.name}>{field.name} · {field.type||'Type not established'} {field.width===undefined?(field.length===undefined?'':`· length ${field.length}`):`· width ${field.width}`} {field.group&&`· group ${field.group}`} {field.storage_section&&`· storage ${field.storage_section}`} {field.source_ref&&`· ${field.source_ref}`}</li>)}</ul><h4>Dependencies ({program.technical_spec.dependency_count})</h4><ul className="compact-list">{program.technical_spec.dependencies.map((item,index)=><li key={index}>{item.name||item.path||'Unresolved dependency'} · {item.kind||'Source dependency'}</li>)}</ul><h4>Observed links ({program.technical_spec.link_count})</h4><ul className="compact-list">{program.technical_spec.links.map((item,index)=><li key={index}>{item.kind} → {item.target} · {item.resolution||'Unverified'}</li>)}</ul>
    {(!program.technical_spec.fields_complete||!program.technical_spec.dependencies_complete||!program.technical_spec.links_complete)&&<p>Technical detail lists are bounded. Retrieve the frozen source and lineage for all entries.</p>}
    <h4>Validation</h4><ul className="compact-list">{program.validation_requirements.map(item=><li key={item}>{item}</li>)}</ul><h4>Current semantic gaps ({program.risk_count})</h4>{program.risks.map((risk,index)=><p key={index}><strong>{risk.kind}</strong>: {risk.message}</p>)}{!program.risks_complete&&<p>Additional gaps remain in the full coverage report.</p>}{Object.entries(program.personas).map(([persona,guidance])=><p key={persona}><strong>{persona}</strong>: {guidance}</p>)}
    </details>
   </article>}
  </details>
 </div>;
}
