import React,{useEffect,useState} from 'react';
import {artifactUrl} from './workflow';

type Counts={total:number;selected:number;verified:number;gaps:number;excluded:number;unclassified:number};
type Filter='all'|'gaps'|'verified'|'excluded';
type Gate={id:string;kind:string;scope:string;program?:string;source_rule_id?:string;reason:string;resolution:string;facts?:Record<string,unknown>;evidence?:string[];details_complete:boolean};
type Rule={cics_screens?:string[];id:string;source_rule_id:string;category:string;status:string;description:string;description_complete:boolean;modernized_behavior:string;behavior_complete:boolean;source_path:string;source_version:string;source_start:number;source_end:number;source_excerpt:string;source_excerpt_complete:boolean;targets:{file:string;version:string;start:number;end:number;text:string;excerpt_complete:boolean;excerpt_available:boolean}[];target_count:number;targets_complete:boolean;tests:string[];tests_count:number;tests_complete:boolean;evidence:Record<string,unknown>[];evidence_count:number;evidence_complete:boolean;memberships:{job:string;step:string;program:string}[];memberships_count:number;memberships_complete:boolean;programs:string[];gaps:Gate[];gap_count:number;gaps_complete:boolean;program_gates:Gate[];program_gate_count:number;program_gates_complete:boolean;diagnostics_recorded:boolean};
export type ComparisonModel={cics_contract_version?:number|null;downloadable_evidence:string[];process_id:string;basis:string;programs:{key:string;program:string;source_path:string;source_version:string;counts:Counts}[];unassigned_count:number;inventory_counts:Counts;counts:Counts;matching_total:number;after:number;limit:number;next_after:number|null;rules:Rule[];process_gates:Gate[];process_gate_count:number;process_gates_complete:boolean;snapshot:{report:string;inventory:string;html:string;coverage:string;inventory_sha256:string;created:string|null}};
const labels:Record<string,string>={converted_verified:'Verified at report acceptance',implemented_unverified:'Python candidate · unverified',identified:'No implementation evidence',blocked:'Verification blocked',excluded_by_requirements:'Selected No · intentionally omitted'};
const filterLabels:[Filter,string][]=[['all','All'],['gaps','Gaps only'],['verified','Verified'],['excluded','Selected No']];

function GateDetails({gate,processId,downloadableEvidence}:{gate:Gate;processId:string;downloadableEvidence:string[]}){
 const facts=gate.facts||{};
 return <div className="comparison-gate"><p><strong>{gate.program&&`${gate.program} · `}{gate.scope==='process'?`Whole-process gate${gate.source_rule_id?` · ${gate.source_rule_id}`:''}`:gate.scope==='program'?'Whole-program gate':gate.scope==='rule'?`Rule gate · ${gate.source_rule_id}`:'Affected source span'}</strong><br/>{gate.reason}</p>
 {gate.kind==='sme_unresolved'&&<p><strong>Returned answer:</strong> {typeof facts.answer==='string'?facts.answer:'Unknown'}<br/><strong>Correction:</strong> {typeof facts.correction==='string'?(facts.correction||'None recorded'):'Unknown'}<br/><strong>Reviewer:</strong> {typeof facts.reviewer==='string'?facts.reviewer:'Unknown'}</p>}
 {facts.credit_scope==='whole_program'&&<p className="fine-print">This rule’s unresolved review prevents whole-program verification credit.</p>}
 {typeof facts.required==='number'&&typeof facts.observed==='number'&&<p className="gap-fact">{facts.observed} of {facts.required} required distinct states observed.</p>}
 {typeof facts.branch==='string'&&<p>Missing branch witness: <strong>{facts.branch}</strong>.</p>}
 {typeof facts.difference_count==='number'&&<p>{facts.difference_count} differing target cases. {Array.isArray(facts.case_ids)&&<>Case IDs: {facts.case_ids.join(', ')}{facts.case_ids_complete===false?' (preview)':''}.</>}</p>}
 <p><strong>Evidence needed to resolve:</strong> {gate.resolution}</p>
 {gate.evidence&&gate.evidence.length>0&&<ul className="comparison-receipts">{gate.evidence.map((path,i)=><li key={i}>{downloadableEvidence.includes(path)?<a href={artifactUrl(processId,path)}>{path}</a>:<span>{path} · preserved local reference</span>}</li>)}</ul>}
 {Object.keys(facts).length>0&&<details><summary>Recorded gate facts</summary><pre>{JSON.stringify(facts,null,2)}</pre></details>}
 {!gate.details_complete&&<p className="fine-print">Some details are abbreviated. The full frozen inventory and receipts retain the evidence.</p>}
 </div>;
}

function ComparisonCard({rule,model}:{rule:Rule;model:ComparisonModel}){
 const no=rule.status==='excluded_by_requirements', gap=rule.gaps.length>0;
 return <article className={`comparison-card${gap?' has-gap':''}`} aria-labelledby={`title-${rule.id}`}>
 <header><div><p className="eyebrow">{rule.category.replaceAll('_',' ')}</p><h3 id={`title-${rule.id}`}>{rule.description}{!rule.description_complete?'…':''}</h3><p className="comparison-owner">{rule.programs.length?rule.programs.join(' · '):'Source outside parsed program ownership'} · {rule.source_rule_id}{rule.cics_screens?.length?` · ${rule.cics_screens.join(' · ')}`:''}</p></div><span className={`comparison-status ${gap?'gap':no?'omitted':'verified'}`}>{labels[rule.status]}</span></header>
 <div className="comparison-columns"><section aria-label="Original source"><h4>{model.cics_contract_version===1?'Mainframe / CICS source logic':'COBOL / source logic'}</h4><p className="comparison-location">{rule.source_path}:{rule.source_start}–{rule.source_end}</p><pre>{rule.source_excerpt}</pre>{!rule.source_excerpt_complete&&<p className="fine-print">Source excerpt abbreviated; full text is in the frozen inventory.</p>}</section>
 <section aria-label="Modernized implementation"><h4>{model.cics_contract_version===1?'Python / FastAPI replacement':'Python replacement'}</h4>{no?<p className="comparison-empty">{rule.modernized_behavior}</p>:rule.targets.length?rule.targets.map((target,i)=><div key={i}><p className="comparison-location">{target.file}:{target.start}–{target.end}</p>{target.excerpt_available?<pre>{target.text||'The recorded target span is empty.'}</pre>:<p className="comparison-empty">Target excerpt was not recorded in this historical report. Inspect the version-bound mapping.</p>}{!target.excerpt_complete&&<p className="fine-print">Python excerpt abbreviated; full text is in the frozen inventory.</p>}</div>):<p className="comparison-empty">No Python implementation evidence is recorded for this span.</p>}{!no&&!rule.targets_complete&&<p className="fine-print">Showing {rule.targets.length} of {rule.target_count} mappings. The full inventory retains all mappings.</p>}{!no&&rule.targets.length>0&&<p className="fine-print">{rule.status==='converted_verified'?'Satisfied the accepted source-derived verification gates.':'Candidate code has not satisfied the verification gates.'}</p>}</section></div>
 {gap&&<section className="comparison-gap" aria-label="Specific conversion gap"><h4>Specific gap</h4><p className="fine-print">Affected source: {rule.source_path}:{rule.source_start}–{rule.source_end}. This location identifies the affected span; program-wide gates below may be the cause.</p>{rule.gaps.map(g=><GateDetails key={g.id} gate={g} processId={model.process_id} downloadableEvidence={model.downloadable_evidence}/>)}{!rule.gaps_complete&&<p className="fine-print">Showing {rule.gaps.length} of {rule.gap_count} recorded gap reasons and process gates. Download the full frozen inventory for every item.</p>}
 {!rule.diagnostics_recorded&&<p className="notice">Some specific diagnostics were not recorded by this historical inventory. Inspect its referenced receipts; specific missing counts are unknown.</p>}
 {rule.program_gate_count>0&&<details><summary>Recorded program and rule gates ({rule.program_gate_count})</summary>{rule.program_gates.map((g,i)=><GateDetails key={`${g.id}-${i}`} gate={g} processId={model.process_id} downloadableEvidence={model.downloadable_evidence}/>)}{!rule.program_gates_complete&&<p>Showing {rule.program_gates.length} of {rule.program_gate_count} gates. Download the full frozen inventory for every gate.</p>}</details>}</section>}
 <details className="comparison-proof"><summary>Versions, tests and evidence</summary><p>Stable comparison ID: {rule.id}</p><p>Source version: <code>{rule.source_version}</code></p>{rule.targets.map((t,i)=><p key={i}>Python version: <code>{t.version}</code> · {t.file}</p>)}<p>{rule.tests_count} recorded test witnesses and {rule.evidence_count} evidence references. Whole-program evidence can be shared across rules.</p>
 {rule.tests.length>0&&<details><summary>Test witness IDs</summary><pre>{rule.tests.join('\n')}</pre>{!rule.tests_complete&&<p>Showing {rule.tests.length} of {rule.tests_count} IDs.</p>}</details>}
 {rule.evidence.length>0&&<details><summary>Evidence references</summary><pre>{JSON.stringify(rule.evidence,null,2)}</pre>{!rule.evidence_complete&&<p>Showing {rule.evidence.length} of {rule.evidence_count} references.</p>}</details>}
 {rule.memberships.length>0&&<p>Job / step: {rule.memberships.map(m=>`${m.job} / ${m.step||'job source'}${m.program?` / ${m.program}`:''}`).join('; ')}{!rule.memberships_complete?` (showing ${rule.memberships.length} of ${rule.memberships_count})`:''}</p>}
 <a href={artifactUrl(model.process_id,model.snapshot.inventory)}>Download full frozen inventory</a></details>
 </article>;
}

export function ComparisonView({model,program,status,loading,error,onProgram,onStatus,onPage,onRetry,onCoverage}:{model:ComparisonModel|null;program:string;status:Filter;loading:boolean;error:string;onProgram:(value:string)=>void;onStatus:(value:Filter)=>void;onPage:(after:number)=>void;onRetry:()=>void;onCoverage:()=>void}){
 return <section className="program-comparison" aria-labelledby="comparison-title"><div className="sectionhead"><div><p className="eyebrow">ACCEPTED CONVERSION EVIDENCE</p><h2 id="comparison-title">{model?.cics_contract_version===1?'Mainframe and Python / FastAPI, side by side':'COBOL and Python, side by side'}</h2><p>Choose a program, then filter the logic you want to inspect.</p>{model?.cics_contract_version===1&&<p className="fine-print">Screen layout verification covers selected character fields and presentation. CICS controller, AID, session and data gaps remain separate.</p>}</div><button onClick={onCoverage}>Full source coverage</button></div>
 <div className="comparison-controls"><label htmlFor="comparison-program">Program<select id="comparison-program" value={program} onChange={e=>onProgram(e.target.value)} disabled={loading||!model||!!error}><option value="">All programs and source</option>{model?.programs.map(p=><option key={p.key} value={p.key}>{p.program} · {p.source_path}</option>)}<option value="unassigned">Source outside parsed programs ({model?.unassigned_count??'unknown'})</option></select></label><div className="comparison-filters" role="group" aria-label="Comparison status">{filterLabels.map(([value,label])=><button key={value} aria-pressed={status===value} disabled={loading||!model||!!error} onClick={()=>onStatus(value)}>{label}</button>)}</div></div>
 {loading?<p role="status">Loading the accepted comparison evidence…</p>:error?<div className="error" role="alert"><p>{error}</p><button onClick={onRetry}>Try loading comparison again</button></div>:model?<>
 <div className="comparison-counts" aria-label="Selected program totals"><div><strong>{model.counts.total}</strong><span>Source units</span></div><div><strong>{model.counts.verified}</strong><span>Verified</span></div><div><strong>{model.counts.gaps}</strong><span>Gaps</span></div><div><strong>{model.counts.excluded}</strong><span>Selected No</span></div></div>
 <p className="fine-print">{model.basis} {model.counts.unclassified>0&&`${model.counts.unclassified} unclassified spans have unknown semantic rule counts. `}Shared copybook units may belong to several programs; the complete inventory has {model.inventory_counts.total} unique units.</p>
 {model.process_gate_count>0&&<details className="comparison-process-gates"><summary>Process-wide gates ({model.process_gate_count})</summary><p>These obligations remain open even when the selected program has no conversion gaps.</p>{model.process_gates.map(g=><GateDetails key={g.id} gate={g} processId={model.process_id} downloadableEvidence={model.downloadable_evidence}/>)}{!model.process_gates_complete&&<p>Showing {model.process_gates.length} of {model.process_gate_count} process gates; the full frozen inventory retains every item.</p>}</details>}
 <div className="comparison-pagehead"><p role="status">{model.matching_total} units match · {model.rules.length?`showing ${model.after+1}–${model.after+model.rules.length}`:'none to show'}</p><a href={artifactUrl(model.process_id,model.snapshot.html)}>Download comparison report</a></div>
 {model.rules.length===0?<div className="empty-state"><h3>No source units match these filters</h3><p>{status==='gaps'?'No gaps are recorded in this selected scope. This does not establish observed mainframe parity.':'Choose All or another program to inspect the retained evidence.'}</p></div>:model.rules.map(rule=><ComparisonCard key={rule.id} rule={rule} model={model}/>)}
 <div className="comparison-pagination" aria-label="Comparison pages"><button disabled={model.after===0} onClick={()=>onPage(Math.max(0,model.after-model.limit))}>Previous page</button><button disabled={model.next_after===null} onClick={()=>model.next_after!==null&&onPage(model.next_after)}>Next page</button></div>
 <details className="fine-print"><summary>Accepted snapshot</summary><p>{model.snapshot.report} · {model.snapshot.created||'Report date unavailable'}</p><p>Inventory SHA-256: <code>{model.snapshot.inventory_sha256}</code></p></details>
 </>:<p>Select a process with an accepted report to inspect the comparison.</p>}
 </section>;
}

export function ProgramComparison({processId,status:processStatus,reportPath,onCoverage}:{processId?:string;status?:string;reportPath?:string|null;onCoverage:()=>void}){
 const [model,setModel]=useState<ComparisonModel|null>(null),[program,setProgram]=useState(''),[status,setStatus]=useState<Filter>('all'),[after,setAfter]=useState(0),[loading,setLoading]=useState(false),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>{setModel(null);setProgram('');setStatus('all');setAfter(0);},[processId,reportPath]);
 useEffect(()=>{if(!processId)return;const controller=new AbortController();let active=true;setLoading(true);setError('');const query=new URLSearchParams({program,status,after:String(after)});
 fetch(`/api/process/${encodeURIComponent(processId)}/comparison?${query}`,{signal:controller.signal}).then(async response=>{const data=await response.json();if(!response.ok)throw Error(data.error||'Accepted comparison unavailable.');if(active)setModel(data);}).catch(e=>{if(active)setError(e instanceof Error?e.message:String(e));}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;controller.abort();};
 },[processId,reportPath,processStatus,program,status,after,retry]);
 return <ComparisonView model={model} program={program} status={status} loading={loading} error={error} onProgram={value=>{setProgram(value);setAfter(0);}} onStatus={value=>{setStatus(value);setAfter(0);}} onPage={setAfter} onRetry={()=>setRetry(v=>v+1)} onCoverage={onCoverage}/>;
}
