import React from 'react';

export function SetupGuidance({questionId}:{questionId:string}){
 if(questionId==='manifest')return <p><a href="/api/templates/intake">Download the editable process intake template</a>. Supply the actual process ID and ordered jobs and steps.</p>;
 if(questionId==='zowe')return <details className="connection-guide"><summary>Prepare a project Zowe profile and secure prompts</summary><ol className="setup-steps"><li>From this repository, run <code>python tools/setup_zowe.py --workspace WORKSPACE --interactive</code> in your local terminal. Replace WORKSPACE with the actual path; the helper prompts for nonsecret profile aliases, z/OSMF host and port. No credentials belong in arguments.</li><li>Run <code>zowe config secure</code> interactively from <code>WORKSPACE</code>, or add <code>--secure</code> to the helper to open these local credential prompts. Zowe prompts locally for user/password from the profile’s <code>secure</code> array; never paste credentials into this questionnaire.</li><li>Set <code>WB_ZOWE_PROFILE</code> and <code>WB_ZOWE_ZOSMF_PROFILE</code> to the actual aliases returned by the helper, then restart. The default pair is <code>workbench_base</code> and <code>workbench_base_zosmf</code>.</li><li>For explicit nonsecret arguments, use <code>python tools/setup_zowe.py --workspace WORKSPACE --profile workbench_base --host ACTUAL_ZOSMF_HOST --port ACTUAL_PORT</code>.</li><li>To preserve explicitly selected project files, use <code>--import-config EXACT_CONFIG --import-schema EXACT_SCHEMA</code> with the helper. For a user config, use <code>--user-config</code> and <code>zowe config secure --user-config</code>.</li></ol><p className="fine-print">Configuration does not certify credentials or live read access. WEDLX and TranRepository are application availability locations; actual datasets and input readiness remain Unknown.</p></details>;
 if(questionId==='db2')return <details className="connection-guide"><summary>Prepare Db2 settings and its CA certificate</summary><ol className="setup-steps"><li>Run <code>python tools/setup_db2.py --workspace WORKSPACE</code> to prepare the nonsecret local connection template.</li><li>Replace host, port and database placeholders in <code>.migration/db2-config.json</code> and set <code>WB_DB2_CONFIG</code> to its exact local path. Replace the certificate placeholder at <code>certificates/DB2-CA.cert</code> with the approved CA certificate. Keep SSL and certificate validation enabled.</li><li>Provide the read-only account privately through the approved secure driver or <code>WB_DB2_USER</code> / <code>WB_DB2_PASSWORD</code>. Keep credentials outside this questionnaire.</li><li>Keep the approved read-only MCP gateway available to GitHub Copilot for requested catalog/file retrieval. Claude Code has no MCP servers and reads the resulting local evidence. Do not add a connection to bypass organization policy.</li></ol><p className="fine-print">A template or certificate path remains unverified until the real driver, trust chain, credentials and approved read access succeed. Setup performs no SQL or network request.</p></details>;
 if(questionId==='llm')return <p className="notice">Claude Code performs local analysis, development, testing and review with no MCP servers, including in the approved VS Code extension. GitHub Copilot only retrieves requested files and metadata through approved MCP connections. Paste the generated retrieval prompt into Copilot, then return to Claude and say Continue. No model endpoint is required; actual credits remain Unknown without receipts.</p>;
 return null;
}
