#!/usr/bin/env python3
"""Regenerate release hashes from official PyPI metadata; no unconstrained resolution.

Run with CPython 3.12 and its bundled pip. Changing these reviewed pins requires
re-running tests and downloading with pip --require-hashes on both platforms.
"""
import argparse
from concurrent.futures import ThreadPoolExecutor
import json
from pathlib import Path
import re
import urllib.request

from pip._vendor.packaging.markers import default_environment
from pip._vendor.packaging.requirements import Requirement
from pip._vendor.packaging.utils import canonicalize_name
from pip._vendor.packaging.version import Version

PINS = {
    'annotated-doc': '0.0.5', 'annotated-types': '0.8.0', 'anyio': '4.15.1',
    'click': '8.5.0', 'et-xmlfile': '2.0.0', 'fastapi': '0.142.2', 'h11': '0.16.0',
    'idna': '3.20', 'lxml': '6.1.3', 'openpyxl': '3.1.5',
    'opentelemetry-api': '1.45.0', 'pillow': '12.3.0', 'pydantic': '2.13.5',
    'pydantic-core': '2.46.5', 'python-docx': '1.2.0', 'python-pptx': '1.0.2',
    'starlette': '1.7.0', 'typing-extensions': '4.16.0', 'typing-inspection': '0.4.4',
    'uvicorn': '0.54.0', 'xlsxwriter': '3.2.9',
}


def release_metadata(entry):
    name, version = entry
    url = f'https://pypi.org/pypi/{name}/{version}/json'
    request = urllib.request.Request(url, headers={'User-Agent': 'workbench-lock/1'})
    with urllib.request.urlopen(request, timeout=45) as response:
        result = json.load(response)
    if (canonicalize_name(result['info']['name']) != name or
            Version(result['info']['version']) != Version(version)):
        raise ValueError(f'Unexpected release identity for {name}')
    return name, result


def validate_dependencies(releases):
    for system, platform in [('Linux', 'linux'), ('Windows', 'win32')]:
        environment = dict(default_environment(), python_version='3.12',
                           python_full_version='3.12.0', platform_system=system,
                           sys_platform=platform, platform_machine='AMD64' if platform=='win32' else 'x86_64',
                           implementation_name='cpython', platform_python_implementation='CPython', extra='')
        for name, release in releases.items():
            python_spec = release['info'].get('requires_python')
            if python_spec:
                from pip._vendor.packaging.specifiers import SpecifierSet
                if not SpecifierSet(python_spec).contains('3.12.0'):
                    raise ValueError(f'{name} does not support Python 3.12')
            for text in release['info'].get('requires_dist') or []:
                dependency = Requirement(text)
                if dependency.marker and not dependency.marker.evaluate(environment):
                    continue
                dep_name = canonicalize_name(dependency.name)
                if dep_name not in PINS or not dependency.specifier.contains(PINS[dep_name]):
                    raise ValueError(f'{system}: missing/incompatible pin for {name}: {text}')


def render_lock(releases):
    lines = [
        '# CPython 3.12 Windows/Linux release lock; generated by tools/lock_dependencies.py.',
        '# SHA256 values are official https://pypi.org/pypi/<name>/<version>/json release digests.',
        '# All non-yanked wheels and sdists are listed; setup uses wheels only to avoid unpinned builds.',
        '# Refresh requires the full validation suite; hashes do not certify vulnerability status.',
        '# Optional live Db2 gateway: install pyodbc separately with your IBM driver.',
    ]
    for name, version in sorted(PINS.items()):
        release = releases[name]
        digests = set()
        for artifact in release['urls']:
            if artifact['yanked'] or artifact['packagetype'] not in ('bdist_wheel', 'sdist'):
                continue
            if not artifact['url'].startswith('https://files.pythonhosted.org/'):
                raise ValueError(f'Unexpected distribution host for {name}')
            digest = artifact['digests']['sha256']
            if not re.fullmatch('[0-9a-f]{64}', digest):
                raise ValueError(f'Invalid published SHA256 for {name}')
            digests.add(digest)
        if not digests:
            raise ValueError(f'No distributions for {name}')
        lines.append(f'{name}=={version} \\')
        ordered = sorted(digests)
        lines.extend(f'    --hash=sha256:{digest}' + (' \\' if i < len(ordered)-1 else '')
                     for i, digest in enumerate(ordered))
    return '\n'.join(lines) + '\n'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Verify existing lock against official release metadata')
    args = parser.parse_args()
    with ThreadPoolExecutor(max_workers=8) as pool:
        releases = dict(pool.map(release_metadata, PINS.items()))
    validate_dependencies(releases)
    contents = render_lock(releases)
    destination = Path(__file__).resolve().parents[1] / 'requirements.lock'
    if args.check:
        if destination.read_text() != contents:
            raise SystemExit('Lock differs from official metadata; regenerate and revalidate')
        print(f'Verified all published SHA256 digests and transitive pins for {len(PINS)} releases')
    else:
        destination.write_text(contents)
        print(f'Wrote {destination}: {len(PINS)} exact pins with published SHA256 digests')


if __name__ == '__main__':
    main()
